// 単語・熟語データベース
// en: 英語, ipa: 発音記号(熟語は省略可), ja: 正解として認める日本語（部分一致で判定）,
// ex/exJa: 例文と訳, lv: レベル(1=中学基礎 2=中学発展 3=高校 4=大学受験 5=上級), k: "w"=単語 "i"=熟語
// 追加したい場合はこの配列に同じ形式で追記するだけでOK
const WORDS = [
  // ===== Lv1 単語（中学基礎） =====
  { en: "important", ipa: "/ɪmˈpɔːrtnt/", ja: ["重要", "大切", "大事"], ex: "This is an important question.", exJa: "これは重要な質問です。", lv: 1, k: "w" },
  { en: "difficult", ipa: "/ˈdɪfɪkəlt/", ja: ["難しい", "困難", "むずかしい"], ex: "Math is difficult for me.", exJa: "数学は私には難しい。", lv: 1, k: "w" },
  { en: "famous", ipa: "/ˈfeɪməs/", ja: ["有名"], ex: "Kyoto is famous for its temples.", exJa: "京都はお寺で有名です。", lv: 1, k: "w" },
  { en: "weather", ipa: "/ˈweðər/", ja: ["天気", "天候"], ex: "The weather is nice today.", exJa: "今日は天気がいい。", lv: 1, k: "w" },
  { en: "vacation", ipa: "/veɪˈkeɪʃn/", ja: ["休暇", "休み", "やすみ"], ex: "We went to Okinawa on vacation.", exJa: "私たちは休暇で沖縄へ行った。", lv: 1, k: "w" },
  { en: "hungry", ipa: "/ˈhʌŋɡri/", ja: ["空腹", "お腹が空いた", "おなかがすいた", "腹が減った"], ex: "I'm hungry. Let's eat lunch.", exJa: "お腹が空いた。昼ごはんを食べよう。", lv: 1, k: "w" },
  { en: "angry", ipa: "/ˈæŋɡri/", ja: ["怒った", "怒っている", "腹を立て", "おこって"], ex: "She was angry with me.", exJa: "彼女は私に怒っていた。", lv: 1, k: "w" },
  { en: "quiet", ipa: "/ˈkwaɪət/", ja: ["静か", "しずか"], ex: "Please be quiet in the library.", exJa: "図書館では静かにしてください。", lv: 1, k: "w" },
  { en: "cheap", ipa: "/tʃiːp/", ja: ["安い", "安価", "やすい"], ex: "This shirt was very cheap.", exJa: "このシャツはとても安かった。", lv: 1, k: "w" },
  { en: "heavy", ipa: "/ˈhevi/", ja: ["重い", "おもい"], ex: "This bag is too heavy.", exJa: "このカバンは重すぎる。", lv: 1, k: "w" },
  { en: "begin", ipa: "/bɪˈɡɪn/", ja: ["始める", "始まる", "開始", "はじめる", "はじまる"], ex: "The class begins at nine.", exJa: "授業は9時に始まる。", lv: 1, k: "w" },
  { en: "build", ipa: "/bɪld/", ja: ["建てる", "建設", "たてる"], ex: "They will build a new school.", exJa: "彼らは新しい学校を建てる予定だ。", lv: 1, k: "w" },
  { en: "carry", ipa: "/ˈkæri/", ja: ["運ぶ", "持ち運ぶ", "はこぶ"], ex: "Can you carry this box?", exJa: "この箱を運んでくれますか。", lv: 1, k: "w" },
  { en: "catch", ipa: "/kætʃ/", ja: ["捕まえる", "捕る", "つかまえる"], ex: "He caught the ball with one hand.", exJa: "彼は片手でボールを捕った。", lv: 1, k: "w" },
  { en: "choose", ipa: "/tʃuːz/", ja: ["選ぶ", "選択", "えらぶ"], ex: "Choose your favorite color.", exJa: "好きな色を選んでください。", lv: 1, k: "w" },
  { en: "answer", ipa: "/ˈænsər/", ja: ["答える", "答え", "回答", "こたえ"], ex: "I don't know the answer.", exJa: "答えがわかりません。", lv: 1, k: "w" },
  { en: "question", ipa: "/ˈkwestʃən/", ja: ["質問", "問い", "しつもん"], ex: "May I ask a question?", exJa: "質問してもいいですか。", lv: 1, k: "w" },
  { en: "holiday", ipa: "/ˈhɑːlədeɪ/", ja: ["休日", "祝日", "休み"], ex: "Monday is a national holiday.", exJa: "月曜日は祝日です。", lv: 1, k: "w" },
  { en: "library", ipa: "/ˈlaɪbreri/", ja: ["図書館", "としょかん"], ex: "I study at the library.", exJa: "私は図書館で勉強します。", lv: 1, k: "w" },
  { en: "hospital", ipa: "/ˈhɑːspɪtl/", ja: ["病院", "びょういん"], ex: "My aunt works at a hospital.", exJa: "おばは病院で働いています。", lv: 1, k: "w" },
  { en: "station", ipa: "/ˈsteɪʃn/", ja: ["駅", "えき"], ex: "The station is near my house.", exJa: "駅は家の近くにあります。", lv: 1, k: "w" },
  { en: "breakfast", ipa: "/ˈbrekfəst/", ja: ["朝食", "朝ごはん", "朝ご飯", "あさごはん"], ex: "I eat breakfast every morning.", exJa: "私は毎朝、朝食を食べます。", lv: 1, k: "w" },
  { en: "dinner", ipa: "/ˈdɪnər/", ja: ["夕食", "晩ごはん", "晩ご飯", "夕飯", "ゆうしょく"], ex: "We had curry for dinner.", exJa: "夕食にカレーを食べた。", lv: 1, k: "w" },
  { en: "tomorrow", ipa: "/təˈmɑːroʊ/", ja: ["明日", "あした", "あす"], ex: "See you tomorrow.", exJa: "また明日。", lv: 1, k: "w" },
  { en: "yesterday", ipa: "/ˈjestərdeɪ/", ja: ["昨日", "きのう"], ex: "It rained yesterday.", exJa: "昨日は雨が降った。", lv: 1, k: "w" },
  { en: "together", ipa: "/təˈɡeðər/", ja: ["一緒に", "共に", "いっしょ"], ex: "Let's have lunch together.", exJa: "一緒に昼食を食べましょう。", lv: 1, k: "w" },

  // ===== Lv2 単語（中学発展） =====
  { en: "foreign", ipa: "/ˈfɔːrən/", ja: ["外国", "海外"], ex: "She speaks three foreign languages.", exJa: "彼女は3つの外国語を話す。", lv: 2, k: "w" },
  { en: "dangerous", ipa: "/ˈdeɪndʒərəs/", ja: ["危険", "危ない", "あぶない"], ex: "Swimming here is dangerous.", exJa: "ここで泳ぐのは危険です。", lv: 2, k: "w" },
  { en: "expensive", ipa: "/ɪkˈspensɪv/", ja: ["高い", "高価", "値段が高い"], ex: "This watch is too expensive.", exJa: "この時計は高すぎる。", lv: 2, k: "w" },
  { en: "arrive", ipa: "/əˈraɪv/", ja: ["到着", "着く", "つく"], ex: "The train arrived on time.", exJa: "電車は時間どおりに到着した。", lv: 2, k: "w" },
  { en: "borrow", ipa: "/ˈbɑːroʊ/", ja: ["借りる", "かりる"], ex: "Can I borrow your pen?", exJa: "ペンを借りてもいい?", lv: 2, k: "w" },
  { en: "invite", ipa: "/ɪnˈvaɪt/", ja: ["招待", "招く", "誘う", "さそう"], ex: "She invited me to the party.", exJa: "彼女は私をパーティーに招待した。", lv: 2, k: "w" },
  { en: "decide", ipa: "/dɪˈsaɪd/", ja: ["決める", "決定", "決心", "きめる"], ex: "I decided to study abroad.", exJa: "私は留学することに決めた。", lv: 2, k: "w" },
  { en: "forget", ipa: "/fərˈɡet/", ja: ["忘れる", "わすれる"], ex: "Don't forget your umbrella.", exJa: "傘を忘れないで。", lv: 2, k: "w" },
  { en: "remember", ipa: "/rɪˈmembər/", ja: ["覚える", "思い出す", "覚えている", "おぼえる"], ex: "I remember his name.", exJa: "彼の名前を覚えています。", lv: 2, k: "w" },
  { en: "healthy", ipa: "/ˈhelθi/", ja: ["健康"], ex: "Vegetables are good for a healthy body.", exJa: "野菜は健康な体に良い。", lv: 2, k: "w" },
  { en: "useful", ipa: "/ˈjuːsfl/", ja: ["役に立つ", "便利", "有用", "やくにたつ"], ex: "This app is very useful.", exJa: "このアプリはとても役に立つ。", lv: 2, k: "w" },
  { en: "careful", ipa: "/ˈkerfl/", ja: ["注意深い", "慎重", "気をつけ"], ex: "Be careful when you cross the street.", exJa: "道を渡るときは気をつけて。", lv: 2, k: "w" },
  { en: "bright", ipa: "/braɪt/", ja: ["明るい", "輝いて", "あかるい"], ex: "The moon is bright tonight.", exJa: "今夜は月が明るい。", lv: 2, k: "w" },
  { en: "museum", ipa: "/mjuˈziːəm/", ja: ["博物館", "美術館"], ex: "We visited the museum last week.", exJa: "先週、博物館を訪れた。", lv: 2, k: "w" },

  // ===== Lv3 単語（高校） =====
  { en: "improve", ipa: "/ɪmˈpruːv/", ja: ["改善", "上達", "向上", "良くする"], ex: "I want to improve my English.", exJa: "英語を上達させたい。", lv: 3, k: "w" },
  { en: "increase", ipa: "/ɪnˈkriːs/", ja: ["増加", "増える", "増やす", "ふえる"], ex: "Prices are increasing every year.", exJa: "物価は毎年上がっている。", lv: 3, k: "w" },
  { en: "decrease", ipa: "/dɪˈkriːs/", ja: ["減少", "減る", "減らす", "へる"], ex: "The population is decreasing.", exJa: "人口は減少している。", lv: 3, k: "w" },
  { en: "suggest", ipa: "/səˈdʒest/", ja: ["提案", "示唆", "勧める"], ex: "He suggested a new plan.", exJa: "彼は新しい計画を提案した。", lv: 3, k: "w" },
  { en: "avoid", ipa: "/əˈvɔɪd/", ja: ["避ける", "回避", "さける"], ex: "You should avoid eating too much.", exJa: "食べ過ぎは避けるべきだ。", lv: 3, k: "w" },
  { en: "achieve", ipa: "/əˈtʃiːv/", ja: ["達成", "成し遂げる", "なしとげる"], ex: "She achieved her goal at last.", exJa: "彼女はついに目標を達成した。", lv: 3, k: "w" },
  { en: "allow", ipa: "/əˈlaʊ/", ja: ["許す", "許可", "ゆるす"], ex: "Smoking is not allowed here.", exJa: "ここでは喫煙は許可されていない。", lv: 3, k: "w" },
  { en: "appear", ipa: "/əˈpɪr/", ja: ["現れる", "登場", "のように見える", "あらわれる"], ex: "A rainbow appeared in the sky.", exJa: "空に虹が現れた。", lv: 3, k: "w" },
  { en: "compare", ipa: "/kəmˈper/", ja: ["比較", "比べる", "くらべる"], ex: "Compare the two pictures.", exJa: "2枚の写真を比べなさい。", lv: 3, k: "w" },
  { en: "consider", ipa: "/kənˈsɪdər/", ja: ["考慮", "よく考える", "検討", "みなす"], ex: "We must consider the cost.", exJa: "費用を考慮しなければならない。", lv: 3, k: "w" },
  { en: "continue", ipa: "/kənˈtɪnjuː/", ja: ["続ける", "継続", "続く", "つづける"], ex: "The rain continued all day.", exJa: "雨は一日中続いた。", lv: 3, k: "w" },
  { en: "create", ipa: "/kriˈeɪt/", ja: ["創造", "作り出す", "生み出す", "つくりだす"], ex: "The artist created a new work.", exJa: "その芸術家は新しい作品を生み出した。", lv: 3, k: "w" },
  { en: "describe", ipa: "/dɪˈskraɪb/", ja: ["描写", "説明する", "述べる"], ex: "Can you describe the man?", exJa: "その男の特徴を説明できますか。", lv: 3, k: "w" },
  { en: "develop", ipa: "/dɪˈveləp/", ja: ["発達", "開発", "発展"], ex: "The company developed a new product.", exJa: "その会社は新製品を開発した。", lv: 3, k: "w" },
  { en: "discover", ipa: "/dɪˈskʌvər/", ja: ["発見", "見つける", "みつける"], ex: "They discovered a new island.", exJa: "彼らは新しい島を発見した。", lv: 3, k: "w" },
  { en: "encourage", ipa: "/ɪnˈkɜːrɪdʒ/", ja: ["励ます", "促す", "勧める", "はげます"], ex: "My teacher encouraged me to try.", exJa: "先生は挑戦するよう励ましてくれた。", lv: 3, k: "w" },
  { en: "environment", ipa: "/ɪnˈvaɪrənmənt/", ja: ["環境", "かんきょう"], ex: "We must protect the environment.", exJa: "私たちは環境を守らなければならない。", lv: 3, k: "w" },
  { en: "experience", ipa: "/ɪkˈspɪriəns/", ja: ["経験", "体験", "けいけん"], ex: "It was a great experience for me.", exJa: "それは私にとって素晴らしい経験だった。", lv: 3, k: "w" },
  { en: "explain", ipa: "/ɪkˈspleɪn/", ja: ["説明", "せつめい"], ex: "Please explain the rule again.", exJa: "そのルールをもう一度説明してください。", lv: 3, k: "w" },
  { en: "express", ipa: "/ɪkˈspres/", ja: ["表現", "表す", "あらわす"], ex: "It's hard to express my feelings.", exJa: "気持ちを表現するのは難しい。", lv: 3, k: "w" },
  { en: "government", ipa: "/ˈɡʌvərnmənt/", ja: ["政府", "せいふ"], ex: "The government announced a new policy.", exJa: "政府は新しい政策を発表した。", lv: 3, k: "w" },
  { en: "include", ipa: "/ɪnˈkluːd/", ja: ["含む", "含める", "ふくむ"], ex: "The price includes tax.", exJa: "価格には税金が含まれています。", lv: 3, k: "w" },
  { en: "knowledge", ipa: "/ˈnɑːlɪdʒ/", ja: ["知識", "ちしき"], ex: "He has a wide knowledge of history.", exJa: "彼は歴史の幅広い知識を持っている。", lv: 3, k: "w" },
  { en: "language", ipa: "/ˈlæŋɡwɪdʒ/", ja: ["言語", "言葉", "げんご"], ex: "English is a world language.", exJa: "英語は世界の言語だ。", lv: 3, k: "w" },
  { en: "necessary", ipa: "/ˈnesəseri/", ja: ["必要", "ひつよう"], ex: "Sleep is necessary for health.", exJa: "睡眠は健康に必要だ。", lv: 3, k: "w" },
  { en: "opinion", ipa: "/əˈpɪnjən/", ja: ["意見", "見解", "いけん"], ex: "In my opinion, he is right.", exJa: "私の意見では、彼は正しい。", lv: 3, k: "w" },
  { en: "opportunity", ipa: "/ˌɑːpərˈtuːnəti/", ja: ["機会", "チャンス", "きかい"], ex: "Don't miss this opportunity.", exJa: "この機会を逃さないで。", lv: 3, k: "w" },
  { en: "prepare", ipa: "/prɪˈper/", ja: ["準備", "用意", "じゅんび"], ex: "I'm preparing for the exam.", exJa: "試験の準備をしています。", lv: 3, k: "w" },
  { en: "protect", ipa: "/prəˈtekt/", ja: ["守る", "保護", "まもる"], ex: "Wear a helmet to protect your head.", exJa: "頭を守るためにヘルメットをかぶりなさい。", lv: 3, k: "w" },
  { en: "provide", ipa: "/prəˈvaɪd/", ja: ["提供", "供給", "与える"], ex: "The hotel provides free breakfast.", exJa: "そのホテルは無料の朝食を提供する。", lv: 3, k: "w" },
  { en: "realize", ipa: "/ˈriːəlaɪz/", ja: ["気づく", "実現", "きづく", "悟る"], ex: "I realized my mistake.", exJa: "自分の間違いに気づいた。", lv: 3, k: "w" },
  { en: "receive", ipa: "/rɪˈsiːv/", ja: ["受け取る", "受ける", "うけとる"], ex: "I received a letter from her.", exJa: "彼女から手紙を受け取った。", lv: 3, k: "w" },
  { en: "reduce", ipa: "/rɪˈduːs/", ja: ["減らす", "削減", "へらす"], ex: "We should reduce plastic waste.", exJa: "プラスチックごみを減らすべきだ。", lv: 3, k: "w" },
  { en: "require", ipa: "/rɪˈkwaɪər/", ja: ["必要とする", "要求", "求める"], ex: "This job requires experience.", exJa: "この仕事は経験を必要とする。", lv: 3, k: "w" },
  { en: "society", ipa: "/səˈsaɪəti/", ja: ["社会", "しゃかい"], ex: "We live in an aging society.", exJa: "私たちは高齢化社会に生きている。", lv: 3, k: "w" },
  { en: "solve", ipa: "/sɑːlv/", ja: ["解決", "解く", "かいけつ"], ex: "He solved the problem easily.", exJa: "彼はその問題を簡単に解いた。", lv: 3, k: "w" },
  { en: "succeed", ipa: "/səkˈsiːd/", ja: ["成功", "せいこう", "後を継ぐ"], ex: "She succeeded in business.", exJa: "彼女はビジネスで成功した。", lv: 3, k: "w" },
  { en: "support", ipa: "/səˈpɔːrt/", ja: ["支える", "支援", "サポート", "ささえる"], ex: "My family supports my dream.", exJa: "家族は私の夢を支えてくれる。", lv: 3, k: "w" },
  { en: "various", ipa: "/ˈveriəs/", ja: ["さまざま", "様々", "いろいろ", "多様"], ex: "The store sells various kinds of tea.", exJa: "その店はさまざまな種類のお茶を売っている。", lv: 3, k: "w" },
  { en: "recognize", ipa: "/ˈrekəɡnaɪz/", ja: ["認識", "認める", "見分ける", "みとめる"], ex: "I didn't recognize him at first.", exJa: "最初は彼だと気づかなかった。", lv: 3, k: "w" },
  { en: "recently", ipa: "/ˈriːsntli/", ja: ["最近", "近頃", "さいきん"], ex: "I recently moved to Tokyo.", exJa: "最近、東京に引っ越した。", lv: 3, k: "w" },
  { en: "attitude", ipa: "/ˈætɪtuːd/", ja: ["態度", "姿勢", "たいど"], ex: "He has a positive attitude.", exJa: "彼は前向きな態度を持っている。", lv: 3, k: "w" },
  { en: "influence", ipa: "/ˈɪnfluəns/", ja: ["影響", "えいきょう"], ex: "TV has a big influence on children.", exJa: "テレビは子どもに大きな影響を与える。", lv: 3, k: "w" },
  { en: "purpose", ipa: "/ˈpɜːrpəs/", ja: ["目的", "意図", "もくてき"], ex: "What is the purpose of your visit?", exJa: "訪問の目的は何ですか。", lv: 3, k: "w" },
  { en: "average", ipa: "/ˈævərɪdʒ/", ja: ["平均", "へいきん"], ex: "The average temperature is rising.", exJa: "平均気温が上昇している。", lv: 3, k: "w" },

  // ===== Lv4 単語（大学受験） =====
  { en: "abandon", ipa: "/əˈbændən/", ja: ["放棄", "捨てる", "断念", "あきらめる", "見捨てる"], ex: "They abandoned the old plan.", exJa: "彼らは古い計画を断念した。", lv: 4, k: "w" },
  { en: "accomplish", ipa: "/əˈkɑːmplɪʃ/", ja: ["成し遂げる", "達成", "なしとげる"], ex: "She accomplished the difficult task.", exJa: "彼女はその難しい仕事を成し遂げた。", lv: 4, k: "w" },
  { en: "accurate", ipa: "/ˈækjərət/", ja: ["正確", "せいかく"], ex: "The report is not accurate.", exJa: "その報告は正確ではない。", lv: 4, k: "w" },
  { en: "acquire", ipa: "/əˈkwaɪər/", ja: ["獲得", "習得", "得る", "かくとく"], ex: "He acquired new skills at work.", exJa: "彼は仕事で新しい技術を習得した。", lv: 4, k: "w" },
  { en: "anticipate", ipa: "/ænˈtɪsɪpeɪt/", ja: ["予期", "予想", "見越す"], ex: "We anticipate a rise in sales.", exJa: "売上の増加を予想している。", lv: 4, k: "w" },
  { en: "apparent", ipa: "/əˈpærənt/", ja: ["明らか", "見かけ", "あきらか"], ex: "It was apparent that he was tired.", exJa: "彼が疲れているのは明らかだった。", lv: 4, k: "w" },
  { en: "significant", ipa: "/sɪɡˈnɪfɪkənt/", ja: ["重要", "重大", "意義深い", "かなりの"], ex: "There was a significant change.", exJa: "重大な変化があった。", lv: 4, k: "w" },
  { en: "sufficient", ipa: "/səˈfɪʃnt/", ja: ["十分", "じゅうぶん"], ex: "We have sufficient food for a week.", exJa: "1週間分の十分な食料がある。", lv: 4, k: "w" },
  { en: "temporary", ipa: "/ˈtempəreri/", ja: ["一時的", "仮の", "いちじてき"], ex: "This is only a temporary job.", exJa: "これは一時的な仕事にすぎない。", lv: 4, k: "w" },
  { en: "transform", ipa: "/trænsˈfɔːrm/", ja: ["変換", "変える", "変貌", "一変"], ex: "The internet transformed our lives.", exJa: "インターネットは私たちの生活を一変させた。", lv: 4, k: "w" },
  { en: "demonstrate", ipa: "/ˈdemənstreɪt/", ja: ["実証", "示す", "証明", "しめす"], ex: "The study demonstrates the effect.", exJa: "その研究は効果を実証している。", lv: 4, k: "w" },
  { en: "distinguish", ipa: "/dɪˈstɪŋɡwɪʃ/", ja: ["区別", "見分ける", "くべつ"], ex: "Can you distinguish the twins?", exJa: "その双子を見分けられますか。", lv: 4, k: "w" },
  { en: "eliminate", ipa: "/ɪˈlɪmɪneɪt/", ja: ["排除", "取り除く", "削除", "とりのぞく"], ex: "We eliminated all the errors.", exJa: "私たちはすべての誤りを取り除いた。", lv: 4, k: "w" },
  { en: "emphasize", ipa: "/ˈemfəsaɪz/", ja: ["強調", "きょうちょう"], ex: "He emphasized the importance of sleep.", exJa: "彼は睡眠の重要性を強調した。", lv: 4, k: "w" },
  { en: "enhance", ipa: "/ɪnˈhæns/", ja: ["高める", "強化", "向上", "たかめる"], ex: "Exercise enhances your health.", exJa: "運動は健康を向上させる。", lv: 4, k: "w" },
  { en: "evaluate", ipa: "/ɪˈvæljueɪt/", ja: ["評価", "ひょうか"], ex: "Teachers evaluate students' work.", exJa: "教師は生徒の課題を評価する。", lv: 4, k: "w" },
  { en: "predict", ipa: "/prɪˈdɪkt/", ja: ["予測", "予言", "よそく"], ex: "No one can predict the future.", exJa: "誰も未来を予測できない。", lv: 4, k: "w" },
  { en: "prohibit", ipa: "/prəˈhɪbɪt/", ja: ["禁止", "きんし"], ex: "Smoking is prohibited in this area.", exJa: "この区域では喫煙が禁止されている。", lv: 4, k: "w" },
  { en: "obstacle", ipa: "/ˈɑːbstəkl/", ja: ["障害", "妨げ", "しょうがい"], ex: "Fear is the biggest obstacle.", exJa: "恐れこそが最大の障害だ。", lv: 4, k: "w" },
  { en: "negotiate", ipa: "/nɪˈɡoʊʃieɪt/", ja: ["交渉", "こうしょう"], ex: "They negotiated a new contract.", exJa: "彼らは新しい契約を交渉した。", lv: 4, k: "w" },
  { en: "imitate", ipa: "/ˈɪmɪteɪt/", ja: ["模倣", "まねる", "真似"], ex: "Children imitate their parents.", exJa: "子どもは親をまねる。", lv: 4, k: "w" },
  { en: "hypothesis", ipa: "/haɪˈpɑːθəsɪs/", ja: ["仮説", "かせつ"], ex: "The data supports his hypothesis.", exJa: "データは彼の仮説を裏付けている。", lv: 4, k: "w" },
  { en: "reluctant", ipa: "/rɪˈlʌktənt/", ja: ["気が進まない", "嫌がる", "しぶしぶ", "気乗りしない"], ex: "He was reluctant to answer.", exJa: "彼は答えるのを嫌がった。", lv: 4, k: "w" },
  { en: "exaggerate", ipa: "/ɪɡˈzædʒəreɪt/", ja: ["誇張", "大げさ", "こちょう", "おおげさ"], ex: "Don't exaggerate the story.", exJa: "話を大げさにしないで。", lv: 4, k: "w" },

  // ===== Lv5 単語（上級） =====
  { en: "abolish", ipa: "/əˈbɑːlɪʃ/", ja: ["廃止", "はいし"], ex: "The law was abolished last year.", exJa: "その法律は昨年廃止された。", lv: 5, k: "w" },
  { en: "adequate", ipa: "/ˈædɪkwət/", ja: ["十分", "適切", "じゅうぶん"], ex: "The room has adequate space.", exJa: "その部屋には十分な広さがある。", lv: 5, k: "w" },
  { en: "ambiguous", ipa: "/æmˈbɪɡjuəs/", ja: ["あいまい", "曖昧"], ex: "His answer was ambiguous.", exJa: "彼の答えはあいまいだった。", lv: 5, k: "w" },
  { en: "inevitable", ipa: "/ɪnˈevɪtəbl/", ja: ["避けられない", "必然", "さけられない"], ex: "Change is inevitable.", exJa: "変化は避けられない。", lv: 5, k: "w" },
  { en: "undermine", ipa: "/ˌʌndərˈmaɪn/", ja: ["弱める", "損なう", "むしばむ", "そこなう"], ex: "Stress can undermine your health.", exJa: "ストレスは健康を損なうことがある。", lv: 5, k: "w" },
  { en: "vague", ipa: "/veɪɡ/", ja: ["あいまい", "曖昧", "漠然"], ex: "I have only a vague memory of it.", exJa: "それについては漠然とした記憶しかない。", lv: 5, k: "w" },
  { en: "withstand", ipa: "/wɪðˈstænd/", ja: ["耐える", "持ちこたえる", "たえる"], ex: "This building can withstand earthquakes.", exJa: "この建物は地震に耐えられる。", lv: 5, k: "w" },
  { en: "compensate", ipa: "/ˈkɑːmpenseɪt/", ja: ["補償", "補う", "埋め合わせ", "おぎなう"], ex: "Nothing can compensate for the loss.", exJa: "その損失は何をもってしても補えない。", lv: 5, k: "w" },
  { en: "comprehensive", ipa: "/ˌkɑːmprɪˈhensɪv/", ja: ["包括的", "総合的", "ほうかつてき"], ex: "We need a comprehensive plan.", exJa: "包括的な計画が必要だ。", lv: 5, k: "w" },
  { en: "contradict", ipa: "/ˌkɑːntrəˈdɪkt/", ja: ["矛盾", "むじゅん", "反論"], ex: "His actions contradict his words.", exJa: "彼の行動は言葉と矛盾している。", lv: 5, k: "w" },
  { en: "deliberate", ipa: "/dɪˈlɪbərət/", ja: ["意図的", "故意", "慎重"], ex: "It was a deliberate lie.", exJa: "それは意図的な嘘だった。", lv: 5, k: "w" },
  { en: "derive", ipa: "/dɪˈraɪv/", ja: ["由来", "引き出す", "得る", "ゆらい"], ex: "This word derives from Latin.", exJa: "この単語はラテン語に由来する。", lv: 5, k: "w" },
  { en: "devastate", ipa: "/ˈdevəsteɪt/", ja: ["荒廃", "打ちのめす", "壊滅"], ex: "The storm devastated the town.", exJa: "嵐が町を壊滅させた。", lv: 5, k: "w" },
  { en: "diminish", ipa: "/dɪˈmɪnɪʃ/", ja: ["減少", "減らす", "小さくする", "弱まる"], ex: "His influence has diminished.", exJa: "彼の影響力は弱まった。", lv: 5, k: "w" },
  { en: "facilitate", ipa: "/fəˈsɪlɪteɪt/", ja: ["促進", "容易にする", "そくしん"], ex: "The app facilitates communication.", exJa: "そのアプリはコミュニケーションを容易にする。", lv: 5, k: "w" },
  { en: "fluctuate", ipa: "/ˈflʌktʃueɪt/", ja: ["変動", "上下する", "へんどう"], ex: "Prices fluctuate daily.", exJa: "価格は日々変動する。", lv: 5, k: "w" },
  { en: "implement", ipa: "/ˈɪmplɪment/", ja: ["実行", "実施", "導入", "じっし"], ex: "The company implemented a new system.", exJa: "その会社は新しいシステムを導入した。", lv: 5, k: "w" },
  { en: "imply", ipa: "/ɪmˈplaɪ/", ja: ["ほのめかす", "暗示", "示唆", "あんじ"], ex: "Her smile implied agreement.", exJa: "彼女の笑顔は同意を暗示していた。", lv: 5, k: "w" },
  { en: "indispensable", ipa: "/ˌɪndɪˈspensəbl/", ja: ["不可欠", "欠かせない", "ふかけつ"], ex: "Water is indispensable to life.", exJa: "水は生命に不可欠だ。", lv: 5, k: "w" },
  { en: "inhibit", ipa: "/ɪnˈhɪbɪt/", ja: ["抑制", "妨げる", "よくせい"], ex: "Fear inhibits free discussion.", exJa: "恐れは自由な議論を妨げる。", lv: 5, k: "w" },
  { en: "legitimate", ipa: "/lɪˈdʒɪtɪmət/", ja: ["合法", "正当", "せいとう"], ex: "That is a legitimate question.", exJa: "それは正当な質問だ。", lv: 5, k: "w" },
  { en: "manipulate", ipa: "/məˈnɪpjuleɪt/", ja: ["操作", "操る", "あやつる"], ex: "He tried to manipulate the data.", exJa: "彼はデータを操作しようとした。", lv: 5, k: "w" },
  { en: "persist", ipa: "/pərˈsɪst/", ja: ["固執", "持続", "続く", "こだわる"], ex: "If the pain persists, see a doctor.", exJa: "痛みが続くなら医者に診てもらいなさい。", lv: 5, k: "w" },
  { en: "plausible", ipa: "/ˈplɔːzəbl/", ja: ["もっともらしい", "妥当", "ありそう"], ex: "His explanation sounds plausible.", exJa: "彼の説明はもっともらしく聞こえる。", lv: 5, k: "w" },

  // ===== Lv1 熟語 =====
  { en: "give up", ja: ["あきらめる", "諦める", "やめる"], ex: "Don't give up on your dream.", exJa: "夢をあきらめないで。", lv: 1, k: "i" },
  { en: "look for", ja: ["探す", "さがす"], ex: "I'm looking for my keys.", exJa: "鍵を探しています。", lv: 1, k: "i" },
  { en: "get up", ja: ["起きる", "起床", "おきる"], ex: "I get up at six every day.", exJa: "毎日6時に起きます。", lv: 1, k: "i" },
  { en: "put on", ja: ["着る", "身につける", "きる"], ex: "Put on your coat. It's cold.", exJa: "コートを着なさい。寒いよ。", lv: 1, k: "i" },
  { en: "take off", ja: ["脱ぐ", "離陸", "ぬぐ", "りりく"], ex: "Please take off your shoes here.", exJa: "ここで靴を脱いでください。", lv: 1, k: "i" },
  { en: "turn on", ja: ["つける", "電源を入れる", "点ける"], ex: "Turn on the light, please.", exJa: "電気をつけてください。", lv: 1, k: "i" },
  { en: "turn off", ja: ["消す", "電源を切る", "けす"], ex: "Turn off the TV before bed.", exJa: "寝る前にテレビを消しなさい。", lv: 1, k: "i" },
  { en: "pick up", ja: ["拾う", "迎えに行く", "ひろう", "むかえ"], ex: "I'll pick you up at the station.", exJa: "駅まで迎えに行くよ。", lv: 1, k: "i" },

  // ===== Lv2 熟語 =====
  { en: "look forward to", ja: ["楽しみに", "たのしみに"], ex: "I'm looking forward to seeing you.", exJa: "あなたに会えるのを楽しみにしています。", lv: 2, k: "i" },
  { en: "take care of", ja: ["世話", "面倒を見る", "せわ", "めんどう"], ex: "She takes care of her little brother.", exJa: "彼女は弟の世話をしている。", lv: 2, k: "i" },
  { en: "be interested in", ja: ["興味がある", "関心がある", "きょうみ"], ex: "I'm interested in Japanese history.", exJa: "日本の歴史に興味があります。", lv: 2, k: "i" },
  { en: "be good at", ja: ["得意", "上手", "とくい", "じょうず"], ex: "He is good at playing soccer.", exJa: "彼はサッカーが得意だ。", lv: 2, k: "i" },

  // ===== Lv3 熟語 =====
  { en: "come up with", ja: ["思いつく", "考え出す", "おもいつく"], ex: "She came up with a great idea.", exJa: "彼女は素晴らしいアイデアを思いついた。", lv: 3, k: "i" },
  { en: "carry out", ja: ["実行", "実施", "じっこう"], ex: "They carried out the plan.", exJa: "彼らはその計画を実行した。", lv: 3, k: "i" },
  { en: "deal with", ja: ["対処", "扱う", "たいしょ", "あつかう"], ex: "How do you deal with stress?", exJa: "ストレスにどう対処していますか。", lv: 3, k: "i" },
  { en: "depend on", ja: ["頼る", "次第", "依存", "たよる"], ex: "It depends on the weather.", exJa: "それは天気次第です。", lv: 3, k: "i" },
  { en: "figure out", ja: ["理解する", "解決する", "わかる", "見つけ出す"], ex: "I can't figure out this problem.", exJa: "この問題が理解できない。", lv: 3, k: "i" },
  { en: "find out", ja: ["見つけ出す", "発見", "知る", "突き止める"], ex: "I found out the truth at last.", exJa: "ついに真実を知った。", lv: 3, k: "i" },
  { en: "get along with", ja: ["仲良く", "うまくやる", "なかよく"], ex: "I get along with my classmates.", exJa: "クラスメートと仲良くやっています。", lv: 3, k: "i" },
  { en: "get rid of", ja: ["取り除く", "処分", "とりのぞく"], ex: "I want to get rid of old clothes.", exJa: "古い服を処分したい。", lv: 3, k: "i" },
  { en: "give in", ja: ["屈する", "降参", "こうさん", "折れる"], ex: "He never gives in to pressure.", exJa: "彼は決して圧力に屈しない。", lv: 3, k: "i" },
  { en: "go through", ja: ["経験", "通り抜ける", "けいけん"], ex: "She went through a hard time.", exJa: "彼女はつらい時期を経験した。", lv: 3, k: "i" },
  { en: "hand in", ja: ["提出", "ていしゅつ"], ex: "Hand in your homework by Friday.", exJa: "金曜日までに宿題を提出しなさい。", lv: 3, k: "i" },
  { en: "look after", ja: ["世話", "面倒を見る", "せわ"], ex: "Can you look after my dog?", exJa: "犬の面倒を見てくれますか。", lv: 3, k: "i" },
  { en: "look up to", ja: ["尊敬", "そんけい"], ex: "I look up to my grandfather.", exJa: "私は祖父を尊敬している。", lv: 3, k: "i" },
  { en: "look down on", ja: ["見下す", "軽蔑", "みくだす", "けいべつ"], ex: "Don't look down on others.", exJa: "他人を見下してはいけない。", lv: 3, k: "i" },
  { en: "make up for", ja: ["埋め合わせ", "補う", "うめあわせ", "おぎなう"], ex: "I'll make up for the lost time.", exJa: "失った時間を埋め合わせます。", lv: 3, k: "i" },
  { en: "put off", ja: ["延期", "先延ばし", "えんき"], ex: "The game was put off until Sunday.", exJa: "試合は日曜日に延期された。", lv: 3, k: "i" },
  { en: "put up with", ja: ["我慢", "耐える", "がまん", "たえる"], ex: "I can't put up with the noise.", exJa: "その騒音には我慢できない。", lv: 3, k: "i" },
  { en: "run out of", ja: ["使い果たす", "切らす", "なくなる", "尽きる"], ex: "We ran out of milk.", exJa: "牛乳を切らしてしまった。", lv: 3, k: "i" },
  { en: "set up", ja: ["設立", "設置", "準備", "せつりつ"], ex: "They set up a new company.", exJa: "彼らは新しい会社を設立した。", lv: 3, k: "i" },
  { en: "show up", ja: ["現れる", "姿を見せる", "あらわれる", "来る"], ex: "He didn't show up at the meeting.", exJa: "彼は会議に現れなかった。", lv: 3, k: "i" },
  { en: "take after", ja: ["似ている", "にている"], ex: "She takes after her mother.", exJa: "彼女は母親に似ている。", lv: 3, k: "i" },
  { en: "take part in", ja: ["参加", "さんか"], ex: "I took part in the contest.", exJa: "私はそのコンテストに参加した。", lv: 3, k: "i" },
  { en: "turn down", ja: ["断る", "却下", "ことわる", "音量を下げる"], ex: "She turned down the offer.", exJa: "彼女はその申し出を断った。", lv: 3, k: "i" },

  // ===== Lv4 熟語 =====
  { en: "account for", ja: ["説明する", "占める", "しめる"], ex: "Exports account for 40% of sales.", exJa: "輸出が売上の40%を占める。", lv: 4, k: "i" },
  { en: "bring about", ja: ["引き起こす", "もたらす", "ひきおこす"], ex: "The war brought about great changes.", exJa: "戦争は大きな変化をもたらした。", lv: 4, k: "i" },
  { en: "call off", ja: ["中止", "取りやめ", "ちゅうし"], ex: "The event was called off due to rain.", exJa: "イベントは雨のため中止された。", lv: 4, k: "i" },
  { en: "come across", ja: ["偶然出会う", "出くわす", "ぐうぜん", "見つける"], ex: "I came across an old friend.", exJa: "旧友に偶然出会った。", lv: 4, k: "i" },
  { en: "drop by", ja: ["立ち寄る", "たちよる"], ex: "Drop by my office anytime.", exJa: "いつでも私のオフィスに立ち寄ってください。", lv: 4, k: "i" },
  { en: "fall behind", ja: ["遅れる", "後れを取る", "おくれる"], ex: "He fell behind in his studies.", exJa: "彼は勉強で遅れを取った。", lv: 4, k: "i" },
  { en: "live up to", ja: ["期待に応える", "沿う", "こたえる"], ex: "The movie lived up to my expectations.", exJa: "その映画は期待に応えてくれた。", lv: 4, k: "i" },
  { en: "take over", ja: ["引き継ぐ", "乗っ取る", "ひきつぐ"], ex: "She took over the family business.", exJa: "彼女は家業を引き継いだ。", lv: 4, k: "i" },
  { en: "turn out", ja: ["判明", "だとわかる", "はんめい", "結局"], ex: "The rumor turned out to be true.", exJa: "そのうわさは本当だと判明した。", lv: 4, k: "i" },
  { en: "work out", ja: ["解決", "うまくいく", "運動", "かいけつ"], ex: "Everything worked out fine.", exJa: "すべてうまくいった。", lv: 4, k: "i" },

  // ===== Lv5 熟語 =====
  { en: "do away with", ja: ["廃止", "取り除く", "はいし"], ex: "We should do away with this rule.", exJa: "この規則は廃止すべきだ。", lv: 5, k: "i" },
  { en: "hold back", ja: ["抑える", "ためらう", "おさえる", "隠す"], ex: "She held back her tears.", exJa: "彼女は涙をこらえた。", lv: 5, k: "i" },
  { en: "make out", ja: ["理解する", "見分ける", "わかる"], ex: "I couldn't make out what he said.", exJa: "彼の言ったことが理解できなかった。", lv: 5, k: "i" },
  { en: "rule out", ja: ["除外", "排除", "じょがい"], ex: "We can't rule out that possibility.", exJa: "その可能性は除外できない。", lv: 5, k: "i" },
  { en: "stand for", ja: ["表す", "意味する", "あらわす", "我慢"], ex: "What does AI stand for?", exJa: "AIは何を表していますか。", lv: 5, k: "i" },
];

// 各エントリに一意IDを付与（en + 種別）
WORDS.forEach(w => { w.id = w.k + ":" + w.en; });
