// 単語・熟語データベース
// en: 英語, ja: 正解として認める日本語（部分一致で判定）, lv: レベル(1=中学 2=高校 3=大学受験・上級), k: "w"=単語 "i"=熟語
// 追加したい場合はこの配列に同じ形式で追記するだけでOK
const WORDS = [
  // ===== レベル1 単語（中学レベル） =====
  { en: "important", ja: ["重要", "大切", "大事"], lv: 1, k: "w" },
  { en: "difficult", ja: ["難しい", "困難", "むずかしい"], lv: 1, k: "w" },
  { en: "famous", ja: ["有名"], lv: 1, k: "w" },
  { en: "foreign", ja: ["外国", "海外"], lv: 1, k: "w" },
  { en: "dangerous", ja: ["危険", "危ない", "あぶない"], lv: 1, k: "w" },
  { en: "expensive", ja: ["高い", "高価", "値段が高い"], lv: 1, k: "w" },
  { en: "arrive", ja: ["到着", "着く", "つく"], lv: 1, k: "w" },
  { en: "borrow", ja: ["借りる", "かりる"], lv: 1, k: "w" },
  { en: "invite", ja: ["招待", "招く", "誘う", "さそう"], lv: 1, k: "w" },
  { en: "decide", ja: ["決める", "決定", "決心", "きめる"], lv: 1, k: "w" },
  { en: "forget", ja: ["忘れる", "わすれる"], lv: 1, k: "w" },
  { en: "remember", ja: ["覚える", "思い出す", "覚えている", "おぼえる"], lv: 1, k: "w" },
  { en: "weather", ja: ["天気", "天候"], lv: 1, k: "w" },
  { en: "vacation", ja: ["休暇", "休み", "やすみ"], lv: 1, k: "w" },
  { en: "healthy", ja: ["健康"], lv: 1, k: "w" },
  { en: "hungry", ja: ["空腹", "お腹が空いた", "おなかがすいた", "腹が減った"], lv: 1, k: "w" },
  { en: "angry", ja: ["怒った", "怒っている", "腹を立て", "おこって"], lv: 1, k: "w" },
  { en: "useful", ja: ["役に立つ", "便利", "有用", "やくにたつ"], lv: 1, k: "w" },
  { en: "careful", ja: ["注意深い", "慎重", "気をつけ"], lv: 1, k: "w" },
  { en: "quiet", ja: ["静か", "しずか"], lv: 1, k: "w" },
  { en: "cheap", ja: ["安い", "安価", "やすい"], lv: 1, k: "w" },
  { en: "heavy", ja: ["重い", "おもい"], lv: 1, k: "w" },
  { en: "bright", ja: ["明るい", "輝いて", "あかるい"], lv: 1, k: "w" },
  { en: "begin", ja: ["始める", "始まる", "開始", "はじめる", "はじまる"], lv: 1, k: "w" },
  { en: "build", ja: ["建てる", "建設", "たてる"], lv: 1, k: "w" },
  { en: "carry", ja: ["運ぶ", "持ち運ぶ", "はこぶ"], lv: 1, k: "w" },
  { en: "catch", ja: ["捕まえる", "捕る", "つかまえる"], lv: 1, k: "w" },
  { en: "choose", ja: ["選ぶ", "選択", "えらぶ"], lv: 1, k: "w" },
  { en: "answer", ja: ["答える", "答え", "回答", "こたえ"], lv: 1, k: "w" },
  { en: "question", ja: ["質問", "問い", "しつもん"], lv: 1, k: "w" },
  { en: "holiday", ja: ["休日", "祝日", "休み"], lv: 1, k: "w" },
  { en: "museum", ja: ["博物館", "美術館"], lv: 1, k: "w" },
  { en: "library", ja: ["図書館", "としょかん"], lv: 1, k: "w" },
  { en: "hospital", ja: ["病院", "びょういん"], lv: 1, k: "w" },
  { en: "station", ja: ["駅", "えき"], lv: 1, k: "w" },
  { en: "breakfast", ja: ["朝食", "朝ごはん", "朝ご飯", "あさごはん"], lv: 1, k: "w" },
  { en: "dinner", ja: ["夕食", "晩ごはん", "晩ご飯", "夕飯", "ゆうしょく"], lv: 1, k: "w" },
  { en: "tomorrow", ja: ["明日", "あした", "あす"], lv: 1, k: "w" },
  { en: "yesterday", ja: ["昨日", "きのう"], lv: 1, k: "w" },
  { en: "together", ja: ["一緒に", "共に", "いっしょ"], lv: 1, k: "w" },

  // ===== レベル2 単語（高校レベル） =====
  { en: "improve", ja: ["改善", "上達", "向上", "良くする"], lv: 2, k: "w" },
  { en: "increase", ja: ["増加", "増える", "増やす", "ふえる"], lv: 2, k: "w" },
  { en: "decrease", ja: ["減少", "減る", "減らす", "へる"], lv: 2, k: "w" },
  { en: "suggest", ja: ["提案", "示唆", "勧める"], lv: 2, k: "w" },
  { en: "avoid", ja: ["避ける", "回避", "さける"], lv: 2, k: "w" },
  { en: "achieve", ja: ["達成", "成し遂げる", "なしとげる"], lv: 2, k: "w" },
  { en: "allow", ja: ["許す", "許可", "ゆるす"], lv: 2, k: "w" },
  { en: "appear", ja: ["現れる", "登場", "のように見える", "あらわれる"], lv: 2, k: "w" },
  { en: "compare", ja: ["比較", "比べる", "くらべる"], lv: 2, k: "w" },
  { en: "consider", ja: ["考慮", "よく考える", "検討", "みなす"], lv: 2, k: "w" },
  { en: "continue", ja: ["続ける", "継続", "続く", "つづける"], lv: 2, k: "w" },
  { en: "create", ja: ["創造", "作り出す", "生み出す", "つくりだす"], lv: 2, k: "w" },
  { en: "describe", ja: ["描写", "説明する", "述べる"], lv: 2, k: "w" },
  { en: "develop", ja: ["発達", "開発", "発展"], lv: 2, k: "w" },
  { en: "discover", ja: ["発見", "見つける", "みつける"], lv: 2, k: "w" },
  { en: "encourage", ja: ["励ます", "促す", "勧める", "はげます"], lv: 2, k: "w" },
  { en: "environment", ja: ["環境", "かんきょう"], lv: 2, k: "w" },
  { en: "experience", ja: ["経験", "体験", "けいけん"], lv: 2, k: "w" },
  { en: "explain", ja: ["説明", "せつめい"], lv: 2, k: "w" },
  { en: "express", ja: ["表現", "表す", "あらわす"], lv: 2, k: "w" },
  { en: "government", ja: ["政府", "せいふ"], lv: 2, k: "w" },
  { en: "include", ja: ["含む", "含める", "ふくむ"], lv: 2, k: "w" },
  { en: "knowledge", ja: ["知識", "ちしき"], lv: 2, k: "w" },
  { en: "language", ja: ["言語", "言葉", "げんご"], lv: 2, k: "w" },
  { en: "necessary", ja: ["必要", "ひつよう"], lv: 2, k: "w" },
  { en: "opinion", ja: ["意見", "見解", "いけん"], lv: 2, k: "w" },
  { en: "opportunity", ja: ["機会", "チャンス", "きかい"], lv: 2, k: "w" },
  { en: "prepare", ja: ["準備", "用意", "じゅんび"], lv: 2, k: "w" },
  { en: "protect", ja: ["守る", "保護", "まもる"], lv: 2, k: "w" },
  { en: "provide", ja: ["提供", "供給", "与える"], lv: 2, k: "w" },
  { en: "realize", ja: ["気づく", "実現", "きづく", "悟る"], lv: 2, k: "w" },
  { en: "receive", ja: ["受け取る", "受ける", "うけとる"], lv: 2, k: "w" },
  { en: "reduce", ja: ["減らす", "削減", "へらす"], lv: 2, k: "w" },
  { en: "require", ja: ["必要とする", "要求", "求める"], lv: 2, k: "w" },
  { en: "society", ja: ["社会", "しゃかい"], lv: 2, k: "w" },
  { en: "solve", ja: ["解決", "解く", "かいけつ"], lv: 2, k: "w" },
  { en: "succeed", ja: ["成功", "せいこう", "後を継ぐ"], lv: 2, k: "w" },
  { en: "support", ja: ["支える", "支援", "サポート", "ささえる"], lv: 2, k: "w" },
  { en: "various", ja: ["さまざま", "様々", "いろいろ", "多様"], lv: 2, k: "w" },
  { en: "recognize", ja: ["認識", "認める", "見分ける", "みとめる"], lv: 2, k: "w" },
  { en: "recently", ja: ["最近", "近頃", "さいきん"], lv: 2, k: "w" },
  { en: "attitude", ja: ["態度", "姿勢", "たいど"], lv: 2, k: "w" },
  { en: "influence", ja: ["影響", "えいきょう"], lv: 2, k: "w" },
  { en: "purpose", ja: ["目的", "意図", "もくてき"], lv: 2, k: "w" },
  { en: "average", ja: ["平均", "へいきん"], lv: 2, k: "w" },

  // ===== レベル3 単語（大学受験・上級） =====
  { en: "abandon", ja: ["放棄", "捨てる", "断念", "あきらめる", "見捨てる"], lv: 3, k: "w" },
  { en: "abolish", ja: ["廃止", "はいし"], lv: 3, k: "w" },
  { en: "accomplish", ja: ["成し遂げる", "達成", "なしとげる"], lv: 3, k: "w" },
  { en: "accurate", ja: ["正確", "せいかく"], lv: 3, k: "w" },
  { en: "acquire", ja: ["獲得", "習得", "得る", "かくとく"], lv: 3, k: "w" },
  { en: "adequate", ja: ["十分", "適切", "じゅうぶん"], lv: 3, k: "w" },
  { en: "ambiguous", ja: ["あいまい", "曖昧"], lv: 3, k: "w" },
  { en: "anticipate", ja: ["予期", "予想", "見越す"], lv: 3, k: "w" },
  { en: "apparent", ja: ["明らか", "見かけ", "あきらか"], lv: 3, k: "w" },
  { en: "inevitable", ja: ["避けられない", "必然", "さけられない"], lv: 3, k: "w" },
  { en: "significant", ja: ["重要", "重大", "意義深い", "かなりの"], lv: 3, k: "w" },
  { en: "sufficient", ja: ["十分", "じゅうぶん"], lv: 3, k: "w" },
  { en: "temporary", ja: ["一時的", "仮の", "いちじてき"], lv: 3, k: "w" },
  { en: "transform", ja: ["変換", "変える", "変貌", "一変"], lv: 3, k: "w" },
  { en: "undermine", ja: ["弱める", "損なう", "むしばむ", "そこなう"], lv: 3, k: "w" },
  { en: "vague", ja: ["あいまい", "曖昧", "漠然"], lv: 3, k: "w" },
  { en: "withstand", ja: ["耐える", "持ちこたえる", "たえる"], lv: 3, k: "w" },
  { en: "compensate", ja: ["補償", "補う", "埋め合わせ", "おぎなう"], lv: 3, k: "w" },
  { en: "comprehensive", ja: ["包括的", "総合的", "ほうかつてき"], lv: 3, k: "w" },
  { en: "contradict", ja: ["矛盾", "むじゅん", "反論"], lv: 3, k: "w" },
  { en: "deliberate", ja: ["意図的", "故意", "慎重"], lv: 3, k: "w" },
  { en: "demonstrate", ja: ["実証", "示す", "証明", "しめす"], lv: 3, k: "w" },
  { en: "derive", ja: ["由来", "引き出す", "得る", "ゆらい"], lv: 3, k: "w" },
  { en: "devastate", ja: ["荒廃", "打ちのめす", "壊滅"], lv: 3, k: "w" },
  { en: "diminish", ja: ["減少", "減らす", "小さくする", "弱まる"], lv: 3, k: "w" },
  { en: "distinguish", ja: ["区別", "見分ける", "くべつ"], lv: 3, k: "w" },
  { en: "eliminate", ja: ["排除", "取り除く", "削除", "とりのぞく"], lv: 3, k: "w" },
  { en: "emphasize", ja: ["強調", "きょうちょう"], lv: 3, k: "w" },
  { en: "enhance", ja: ["高める", "強化", "向上", "たかめる"], lv: 3, k: "w" },
  { en: "evaluate", ja: ["評価", "ひょうか"], lv: 3, k: "w" },
  { en: "exaggerate", ja: ["誇張", "大げさ", "こちょう", "おおげさ"], lv: 3, k: "w" },
  { en: "facilitate", ja: ["促進", "容易にする", "そくしん"], lv: 3, k: "w" },
  { en: "fluctuate", ja: ["変動", "上下する", "へんどう"], lv: 3, k: "w" },
  { en: "hypothesis", ja: ["仮説", "かせつ"], lv: 3, k: "w" },
  { en: "imitate", ja: ["模倣", "まねる", "真似"], lv: 3, k: "w" },
  { en: "implement", ja: ["実行", "実施", "導入", "じっし"], lv: 3, k: "w" },
  { en: "imply", ja: ["ほのめかす", "暗示", "示唆", "あんじ"], lv: 3, k: "w" },
  { en: "indispensable", ja: ["不可欠", "欠かせない", "ふかけつ"], lv: 3, k: "w" },
  { en: "inhibit", ja: ["抑制", "妨げる", "よくせい"], lv: 3, k: "w" },
  { en: "legitimate", ja: ["合法", "正当", "せいとう"], lv: 3, k: "w" },
  { en: "manipulate", ja: ["操作", "操る", "あやつる"], lv: 3, k: "w" },
  { en: "negotiate", ja: ["交渉", "こうしょう"], lv: 3, k: "w" },
  { en: "obstacle", ja: ["障害", "妨げ", "しょうがい"], lv: 3, k: "w" },
  { en: "persist", ja: ["固執", "持続", "続く", "こだわる"], lv: 3, k: "w" },
  { en: "plausible", ja: ["もっともらしい", "妥当", "ありそう"], lv: 3, k: "w" },
  { en: "predict", ja: ["予測", "予言", "よそく"], lv: 3, k: "w" },
  { en: "prohibit", ja: ["禁止", "きんし"], lv: 3, k: "w" },
  { en: "reluctant", ja: ["気が進まない", "嫌がる", "しぶしぶ", "気乗りしない"], lv: 3, k: "w" },

  // ===== 熟語 レベル1（中学レベル） =====
  { en: "give up", ja: ["あきらめる", "諦める", "やめる"], lv: 1, k: "i" },
  { en: "look for", ja: ["探す", "さがす"], lv: 1, k: "i" },
  { en: "look forward to", ja: ["楽しみに", "たのしみに"], lv: 1, k: "i" },
  { en: "take care of", ja: ["世話", "面倒を見る", "せわ", "めんどう"], lv: 1, k: "i" },
  { en: "be interested in", ja: ["興味がある", "関心がある", "きょうみ"], lv: 1, k: "i" },
  { en: "be good at", ja: ["得意", "上手", "とくい", "じょうず"], lv: 1, k: "i" },
  { en: "get up", ja: ["起きる", "起床", "おきる"], lv: 1, k: "i" },
  { en: "put on", ja: ["着る", "身につける", "きる"], lv: 1, k: "i" },
  { en: "take off", ja: ["脱ぐ", "離陸", "ぬぐ", "りりく"], lv: 1, k: "i" },
  { en: "turn on", ja: ["つける", "電源を入れる", "点ける"], lv: 1, k: "i" },
  { en: "turn off", ja: ["消す", "電源を切る", "けす"], lv: 1, k: "i" },
  { en: "pick up", ja: ["拾う", "迎えに行く", "ひろう", "むかえ"], lv: 1, k: "i" },

  // ===== 熟語 レベル2（高校レベル） =====
  { en: "come up with", ja: ["思いつく", "考え出す", "おもいつく"], lv: 2, k: "i" },
  { en: "carry out", ja: ["実行", "実施", "じっこう"], lv: 2, k: "i" },
  { en: "deal with", ja: ["対処", "扱う", "たいしょ", "あつかう"], lv: 2, k: "i" },
  { en: "depend on", ja: ["頼る", "次第", "依存", "たよる"], lv: 2, k: "i" },
  { en: "figure out", ja: ["理解する", "解決する", "わかる", "見つけ出す"], lv: 2, k: "i" },
  { en: "find out", ja: ["見つけ出す", "発見", "知る", "突き止める"], lv: 2, k: "i" },
  { en: "get along with", ja: ["仲良く", "うまくやる", "なかよく"], lv: 2, k: "i" },
  { en: "get rid of", ja: ["取り除く", "処分", "とりのぞく"], lv: 2, k: "i" },
  { en: "give in", ja: ["屈する", "降参", "こうさん", "折れる"], lv: 2, k: "i" },
  { en: "go through", ja: ["経験", "通り抜ける", "けいけん"], lv: 2, k: "i" },
  { en: "hand in", ja: ["提出", "ていしゅつ"], lv: 2, k: "i" },
  { en: "look after", ja: ["世話", "面倒を見る", "せわ"], lv: 2, k: "i" },
  { en: "look up to", ja: ["尊敬", "そんけい"], lv: 2, k: "i" },
  { en: "look down on", ja: ["見下す", "軽蔑", "みくだす", "けいべつ"], lv: 2, k: "i" },
  { en: "make up for", ja: ["埋め合わせ", "補う", "うめあわせ", "おぎなう"], lv: 2, k: "i" },
  { en: "put off", ja: ["延期", "先延ばし", "えんき"], lv: 2, k: "i" },
  { en: "put up with", ja: ["我慢", "耐える", "がまん", "たえる"], lv: 2, k: "i" },
  { en: "run out of", ja: ["使い果たす", "切らす", "なくなる", "尽きる"], lv: 2, k: "i" },
  { en: "set up", ja: ["設立", "設置", "準備", "せつりつ"], lv: 2, k: "i" },
  { en: "show up", ja: ["現れる", "姿を見せる", "あらわれる", "来る"], lv: 2, k: "i" },
  { en: "take after", ja: ["似ている", "にている"], lv: 2, k: "i" },
  { en: "take part in", ja: ["参加", "さんか"], lv: 2, k: "i" },
  { en: "turn down", ja: ["断る", "却下", "ことわる", "音量を下げる"], lv: 2, k: "i" },

  // ===== 熟語 レベル3（大学受験・上級） =====
  { en: "account for", ja: ["説明する", "占める", "しめる"], lv: 3, k: "i" },
  { en: "bring about", ja: ["引き起こす", "もたらす", "ひきおこす"], lv: 3, k: "i" },
  { en: "call off", ja: ["中止", "取りやめ", "ちゅうし"], lv: 3, k: "i" },
  { en: "come across", ja: ["偶然出会う", "出くわす", "ぐうぜん", "見つける"], lv: 3, k: "i" },
  { en: "do away with", ja: ["廃止", "取り除く", "はいし"], lv: 3, k: "i" },
  { en: "drop by", ja: ["立ち寄る", "たちよる"], lv: 3, k: "i" },
  { en: "fall behind", ja: ["遅れる", "後れを取る", "おくれる"], lv: 3, k: "i" },
  { en: "hold back", ja: ["抑える", "ためらう", "おさえる", "隠す"], lv: 3, k: "i" },
  { en: "live up to", ja: ["期待に応える", "沿う", "こたえる"], lv: 3, k: "i" },
  { en: "make out", ja: ["理解する", "見分ける", "わかる"], lv: 3, k: "i" },
  { en: "rule out", ja: ["除外", "排除", "じょがい"], lv: 3, k: "i" },
  { en: "stand for", ja: ["表す", "意味する", "あらわす", "我慢"], lv: 3, k: "i" },
  { en: "take over", ja: ["引き継ぐ", "乗っ取る", "ひきつぐ"], lv: 3, k: "i" },
  { en: "turn out", ja: ["判明", "だとわかる", "はんめい", "結局"], lv: 3, k: "i" },
  { en: "work out", ja: ["解決", "うまくいく", "運動", "かいけつ"], lv: 3, k: "i" },
];

// 各エントリに一意IDを付与（en + 種別）
WORDS.forEach(w => { w.id = w.k + ":" + w.en; });
