// 単語・熟語データベース
// en: 英語, ipa: 発音記号(熟語は省略可), ja: 正解として認める日本語（部分一致で判定）,
// ex/exJa: 例文と訳, syn: 類義語(英語・任意), etym: 語源分解 [[部分, 意味], ...](任意),
// lv: レベル(1=中学基礎 2=中学発展 3=高校 4=大学受験 5=上級), k: "w"=単語 "i"=熟語
// 追加したい場合はこの配列に同じ形式で追記するだけでOK
const WORDS = [
  // ===== Lv1 単語（中学基礎） =====
  { en: "important", ipa: "/ɪmˈpɔːrtnt/", ja: ["重要", "大切", "大事"], ex: "This is an important question.", exJa: "これは重要な質問です。", syn: ["significant", "essential"], etym: [["im-", "中へ"], ["port", "運ぶ"], ["-ant", "〜な"]], lv: 1, k: "w" },
  { en: "difficult", ipa: "/ˈdɪfɪkəlt/", ja: ["難しい", "困難", "むずかしい"], ex: "Math is difficult for me.", exJa: "数学は私には難しい。", syn: ["hard", "tough"], etym: [["dif-", "〜でない"], ["facil", "簡単な"], ["-t", "形容詞語尾"]], lv: 1, k: "w" },
  { en: "famous", ipa: "/ˈfeɪməs/", ja: ["有名"], ex: "Kyoto is famous for its temples.", exJa: "京都はお寺で有名です。", syn: ["well-known", "renowned"], etym: [["fam", "評判"], ["-ous", "〜に満ちた"]], lv: 1, k: "w" },
  { en: "weather", ipa: "/ˈweðər/", ja: ["天気", "天候"], ex: "The weather is nice today.", exJa: "今日は天気がいい。", lv: 1, k: "w" },
  { en: "vacation", ipa: "/veɪˈkeɪʃn/", ja: ["休暇", "休み", "やすみ"], ex: "We went to Okinawa on vacation.", exJa: "私たちは休暇で沖縄へ行った。", syn: ["holiday", "break"], etym: [["vac", "空にする"], ["-ation", "〜すること"]], lv: 1, k: "w" },
  { en: "hungry", ipa: "/ˈhʌŋɡri/", ja: ["空腹", "お腹が空いた", "おなかがすいた", "腹が減った"], ex: "I'm hungry. Let's eat lunch.", exJa: "お腹が空いた。昼ごはんを食べよう。", syn: ["starving"], etym: [["hunger", "空腹"], ["-y", "〜の性質を持つ"]], lv: 1, k: "w" },
  { en: "angry", ipa: "/ˈæŋɡri/", ja: ["怒った", "怒っている", "腹を立て", "おこって"], ex: "She was angry with me.", exJa: "彼女は私に怒っていた。", syn: ["mad", "furious"], etym: [["anger", "怒り"], ["-y", "〜の性質を持つ"]], lv: 1, k: "w" },
  { en: "quiet", ipa: "/ˈkwaɪət/", ja: ["静か", "しずか"], ex: "Please be quiet in the library.", exJa: "図書館では静かにしてください。", syn: ["silent", "calm"], etym: [["qui", "休む(quiesに由来)"], ["-et", "形容詞語尾"]], lv: 1, k: "w" },
  { en: "cheap", ipa: "/tʃiːp/", ja: ["安い", "安価", "やすい"], ex: "This shirt was very cheap.", exJa: "このシャツはとても安かった。", syn: ["inexpensive"], etym: [["cheap", "取引(ceapに由来、元は「商売」の意味)"]], lv: 1, k: "w" },
  { en: "heavy", ipa: "/ˈhevi/", ja: ["重い", "おもい"], ex: "This bag is too heavy.", exJa: "このカバンは重すぎる。", syn: ["weighty"], etym: [["heave", "持ち上げる"], ["-y", "〜の性質を持つ"]], lv: 1, k: "w" },
  { en: "begin", ipa: "/bɪˈɡɪn/", ja: ["始める", "始まる", "開始", "はじめる", "はじまる"], ex: "The class begins at nine.", exJa: "授業は9時に始まる。", syn: ["start"], etym: [["be-", "強意"], ["gin", "開く・始める"]], lv: 1, k: "w" },
  { en: "build", ipa: "/bɪld/", ja: ["建てる", "建設", "たてる"], ex: "They will build a new school.", exJa: "彼らは新しい学校を建てる予定だ。", syn: ["construct"], etym: [["build", "住居(byldanに由来)"]], lv: 1, k: "w" },
  { en: "carry", ipa: "/ˈkæri/", ja: ["運ぶ", "持ち運ぶ", "はこぶ"], ex: "Can you carry this box?", exJa: "この箱を運んでくれますか。", syn: ["transport"], etym: [["car", "荷車(carrusに由来)"], ["-ry", "〜する"]], lv: 1, k: "w" },
  { en: "catch", ipa: "/kætʃ/", ja: ["捕まえる", "捕る", "つかまえる"], ex: "He caught the ball with one hand.", exJa: "彼は片手でボールを捕った。", syn: ["grab"], etym: [["cap", "つかむ(capereに由来)"]], lv: 1, k: "w" },
  { en: "choose", ipa: "/tʃuːz/", ja: ["選ぶ", "選択", "えらぶ"], ex: "Choose your favorite color.", exJa: "好きな色を選んでください。", syn: ["select", "pick"], etym: [["choose", "味わって選ぶ(ceosanに由来)"]], lv: 1, k: "w" },
  { en: "answer", ipa: "/ˈænsər/", ja: ["答える", "答え", "回答", "こたえ"], ex: "I don't know the answer.", exJa: "答えがわかりません。", syn: ["reply", "respond"], etym: [["and-", "〜に対して"], ["swer", "誓う(swearの語源)"]], lv: 1, k: "w" },
  { en: "question", ipa: "/ˈkwestʃən/", ja: ["質問", "問い", "しつもん"], ex: "May I ask a question?", exJa: "質問してもいいですか。", syn: ["query"], etym: [["quest", "尋ねる・求める"], ["-ion", "〜すること"]], lv: 1, k: "w" },
  { en: "holiday", ipa: "/ˈhɑːlədeɪ/", ja: ["休日", "祝日", "休み"], ex: "Monday is a national holiday.", exJa: "月曜日は祝日です。", syn: ["vacation", "day off"], etym: [["holy", "神聖な"], ["day", "日"]], lv: 1, k: "w" },
  { en: "library", ipa: "/ˈlaɪbreri/", ja: ["図書館", "としょかん"], ex: "I study at the library.", exJa: "私は図書館で勉強します。", etym: [["libr", "本(liberに由来)"], ["-ary", "〜の場所"]], lv: 1, k: "w" },
  { en: "hospital", ipa: "/ˈhɑːspɪtl/", ja: ["病院", "びょういん"], ex: "My aunt works at a hospital.", exJa: "おばは病院で働いています。", etym: [["hospit", "客をもてなす(hospesに由来)"], ["-al", "〜の場所"]], lv: 1, k: "w" },
  { en: "station", ipa: "/ˈsteɪʃn/", ja: ["駅", "えき"], ex: "The station is near my house.", exJa: "駅は家の近くにあります。", etym: [["sta", "立つ(stareに由来)"], ["-tion", "〜する場所・こと"]], lv: 1, k: "w" },
  { en: "breakfast", ipa: "/ˈbrekfəst/", ja: ["朝食", "朝ごはん", "朝ご飯", "あさごはん"], ex: "I eat breakfast every morning.", exJa: "私は毎朝、朝食を食べます。", etym: [["break", "破る"], ["fast", "断食"]], lv: 1, k: "w" },
  { en: "dinner", ipa: "/ˈdɪnər/", ja: ["夕食", "晩ごはん", "晩ご飯", "夕飯", "ゆうしょく"], ex: "We had curry for dinner.", exJa: "夕食にカレーを食べた。", syn: ["supper"], etym: [["dis-", "否定"], ["jeju(n)", "断食(jejunusに由来)"]], lv: 1, k: "w" },
  { en: "tomorrow", ipa: "/təˈmɑːroʊ/", ja: ["明日", "あした", "あす"], ex: "See you tomorrow.", exJa: "また明日。", etym: [["to", "〜へ"], ["morrow", "翌朝"]], lv: 1, k: "w" },
  { en: "yesterday", ipa: "/ˈjestərdeɪ/", ja: ["昨日", "きのう"], ex: "It rained yesterday.", exJa: "昨日は雨が降った。", etym: [["yester", "昨日の"], ["day", "日"]], lv: 1, k: "w" },
  { en: "together", ipa: "/təˈɡeðər/", ja: ["一緒に", "共に", "いっしょ"], ex: "Let's have lunch together.", exJa: "一緒に昼食を食べましょう。", syn: ["jointly"], etym: [["to", "〜へ"], ["gather", "集める"]], lv: 1, k: "w" },

  // ===== Lv2 単語（中学発展） =====
  { en: "foreign", ipa: "/ˈfɔːrən/", ja: ["外国", "海外"], ex: "She speaks three foreign languages.", exJa: "彼女は3つの外国語を話す。", syn: ["overseas"], etym: [["for-", "外の(forisに由来)"], ["-eign", "〜の"]], lv: 2, k: "w" },
  { en: "dangerous", ipa: "/ˈdeɪndʒərəs/", ja: ["危険", "危ない", "あぶない"], ex: "Swimming here is dangerous.", exJa: "ここで泳ぐのは危険です。", syn: ["risky", "hazardous"], etym: [["danger", "危険"], ["-ous", "〜に満ちた"]], lv: 2, k: "w" },
  { en: "expensive", ipa: "/ɪkˈspensɪv/", ja: ["高い", "高価", "値段が高い"], ex: "This watch is too expensive.", exJa: "この時計は高すぎる。", syn: ["costly", "pricey"], etym: [["ex-", "外へ"], ["pens", "支払う(pendereに由来)"], ["-ive", "〜の性質"]], lv: 2, k: "w" },
  { en: "arrive", ipa: "/əˈraɪv/", ja: ["到着", "着く", "つく"], ex: "The train arrived on time.", exJa: "電車は時間どおりに到着した。", syn: ["reach", "get to"], etym: [["ar-", "〜へ(ad-)"], ["riv", "岸(ripaに由来)"]], lv: 2, k: "w" },
  { en: "borrow", ipa: "/ˈbɑːroʊ/", ja: ["借りる", "かりる"], ex: "Can I borrow your pen?", exJa: "ペンを借りてもいい?", etym: [["borrow", "担保(borgに由来)"]], lv: 2, k: "w" },
  { en: "invite", ipa: "/ɪnˈvaɪt/", ja: ["招待", "招く", "誘う", "さそう"], ex: "She invited me to the party.", exJa: "彼女は私をパーティーに招待した。", syn: ["ask", "welcome"], etym: [["in-", "中へ"], ["vite", "招く(invitareに由来)"]], lv: 2, k: "w" },
  { en: "decide", ipa: "/dɪˈsaɪd/", ja: ["決める", "決定", "決心", "きめる"], ex: "I decided to study abroad.", exJa: "私は留学することに決めた。", syn: ["determine", "resolve"], etym: [["de-", "切り離す"], ["cide", "切る(caedereに由来)"]], lv: 2, k: "w" },
  { en: "forget", ipa: "/fərˈɡet/", ja: ["忘れる", "わすれる"], ex: "Don't forget your umbrella.", exJa: "傘を忘れないで。", etym: [["for-", "失う・逃す"], ["get", "得る"]], lv: 2, k: "w" },
  { en: "remember", ipa: "/rɪˈmembər/", ja: ["覚える", "思い出す", "覚えている", "おぼえる"], ex: "I remember his name.", exJa: "彼の名前を覚えています。", syn: ["recall", "recollect"], etym: [["re-", "再び"], ["member", "記憶する(memorに由来)"]], lv: 2, k: "w" },
  { en: "healthy", ipa: "/ˈhelθi/", ja: ["健康"], ex: "Vegetables are good for a healthy body.", exJa: "野菜は健康な体に良い。", syn: ["fit", "well"], etym: [["heal", "健康(halに由来)"], ["-thy", "〜の性質"]], lv: 2, k: "w" },
  { en: "useful", ipa: "/ˈjuːsfl/", ja: ["役に立つ", "便利", "有用", "やくにたつ"], ex: "This app is very useful.", exJa: "このアプリはとても役に立つ。", syn: ["helpful", "handy"], etym: [["use", "使う"], ["-ful", "〜に満ちた"]], lv: 2, k: "w" },
  { en: "careful", ipa: "/ˈkerfl/", ja: ["注意深い", "慎重", "気をつけ"], ex: "Be careful when you cross the street.", exJa: "道を渡るときは気をつけて。", syn: ["cautious", "attentive"], etym: [["care", "注意"], ["-ful", "〜に満ちた"]], lv: 2, k: "w" },
  { en: "bright", ipa: "/braɪt/", ja: ["明るい", "輝いて", "あかるい"], ex: "The moon is bright tonight.", exJa: "今夜は月が明るい。", syn: ["shining", "vivid"], etym: [["bright", "輝く(beorhtに由来)"]], lv: 2, k: "w" },
  { en: "museum", ipa: "/mjuˈziːəm/", ja: ["博物館", "美術館"], ex: "We visited the museum last week.", exJa: "先週、博物館を訪れた。", etym: [["muse", "ミューズ(学芸の女神)"], ["-um", "場所"]], lv: 2, k: "w" },

  // ===== Lv3 単語（高校） =====
  { en: "improve", ipa: "/ɪmˈpruːv/", ja: ["改善", "上達", "向上", "良くする"], ex: "I want to improve my English.", exJa: "英語を上達させたい。", syn: ["enhance", "better"], etym: [["im-", "強意"], ["prove", "利益にする(prodeに由来)"]], lv: 3, k: "w" },
  { en: "increase", ipa: "/ɪnˈkriːs/", ja: ["増加", "増える", "増やす", "ふえる"], ex: "Prices are increasing every year.", exJa: "物価は毎年上がっている。", syn: ["rise", "grow"], etym: [["in-", "中で"], ["crease", "成長する(crescereに由来)"]], lv: 3, k: "w" },
  { en: "decrease", ipa: "/dɪˈkriːs/", ja: ["減少", "減る", "減らす", "へる"], ex: "The population is decreasing.", exJa: "人口は減少している。", syn: ["decline", "reduce"], etym: [["de-", "下へ・減少"], ["crease", "成長する(crescereに由来)"]], lv: 3, k: "w" },
  { en: "suggest", ipa: "/səˈdʒest/", ja: ["提案", "示唆", "勧める"], ex: "He suggested a new plan.", exJa: "彼は新しい計画を提案した。", syn: ["propose", "recommend"], etym: [["sub-", "下から"], ["gest", "運ぶ(gerereに由来)"]], lv: 3, k: "w" },
  { en: "avoid", ipa: "/əˈvɔɪd/", ja: ["避ける", "回避", "さける"], ex: "You should avoid eating too much.", exJa: "食べ過ぎは避けるべきだ。", syn: ["evade", "prevent"], etym: [["a-", "離れて(ex-)"], ["void", "空にする"]], lv: 3, k: "w" },
  { en: "achieve", ipa: "/əˈtʃiːv/", ja: ["達成", "成し遂げる", "なしとげる"], ex: "She achieved her goal at last.", exJa: "彼女はついに目標を達成した。", syn: ["attain", "accomplish"], etym: [["a-", "〜へ(ad-)"], ["chieve", "頭・仕上げ(chefに由来)"]], lv: 3, k: "w" },
  { en: "allow", ipa: "/əˈlaʊ/", ja: ["許す", "許可", "ゆるす"], ex: "Smoking is not allowed here.", exJa: "ここでは喫煙は許可されていない。", syn: ["permit", "let"], etym: [["al-", "〜へ(ad-)"], ["low", "認める・置く(locareに由来)"]], lv: 3, k: "w" },
  { en: "appear", ipa: "/əˈpɪr/", ja: ["現れる", "登場", "のように見える", "あらわれる"], ex: "A rainbow appeared in the sky.", exJa: "空に虹が現れた。", syn: ["seem", "emerge"], etym: [["ap-", "〜へ(ad-)"], ["pear", "現れる(parereに由来)"]], lv: 3, k: "w" },
  { en: "compare", ipa: "/kəmˈper/", ja: ["比較", "比べる", "くらべる"], ex: "Compare the two pictures.", exJa: "2枚の写真を比べなさい。", syn: ["contrast"], etym: [["com-", "共に"], ["pare", "対等にする(parに由来)"]], lv: 3, k: "w" },
  { en: "consider", ipa: "/kənˈsɪdər/", ja: ["考慮", "よく考える", "検討", "みなす"], ex: "We must consider the cost.", exJa: "費用を考慮しなければならない。", syn: ["contemplate", "regard"], etym: [["con-", "共に"], ["sider", "星(sidusに由来)"]], lv: 3, k: "w" },
  { en: "continue", ipa: "/kənˈtɪnjuː/", ja: ["続ける", "継続", "続く", "つづける"], ex: "The rain continued all day.", exJa: "雨は一日中続いた。", syn: ["proceed", "carry on"], etym: [["con-", "共に"], ["tinue", "保つ(tenereに由来)"]], lv: 3, k: "w" },
  { en: "create", ipa: "/kriˈeɪt/", ja: ["創造", "作り出す", "生み出す", "つくりだす", "つくる", "作る"], ex: "The artist created a new work.", exJa: "その芸術家は新しい作品を生み出した。", syn: ["produce", "generate"], etym: [["cre", "生む(crescereに由来)"], ["-ate", "〜にする"]], lv: 3, k: "w" },
  { en: "describe", ipa: "/dɪˈskraɪb/", ja: ["描写", "説明する", "述べる"], ex: "Can you describe the man?", exJa: "その男の特徴を説明できますか。", syn: ["depict", "portray"], etym: [["de-", "下に"], ["scribe", "書く"]], lv: 3, k: "w" },
  { en: "develop", ipa: "/dɪˈveləp/", ja: ["発達", "開発", "発展"], ex: "The company developed a new product.", exJa: "その会社は新製品を開発した。", syn: ["evolve", "advance"], etym: [["de-", "否定・除去"], ["velop", "包む(voloperに由来)"]], lv: 3, k: "w" },
  { en: "discover", ipa: "/dɪˈskʌvər/", ja: ["発見", "見つける", "みつける"], ex: "They discovered a new island.", exJa: "彼らは新しい島を発見した。", syn: ["find", "uncover"], etym: [["dis-", "否定"], ["cover", "覆う"]], lv: 3, k: "w" },
  { en: "encourage", ipa: "/ɪnˈkɜːrɪdʒ/", ja: ["励ます", "促す", "勧める", "はげます"], ex: "My teacher encouraged me to try.", exJa: "先生は挑戦するよう励ましてくれた。", syn: ["motivate", "inspire"], etym: [["en-", "〜にする"], ["courage", "勇気"]], lv: 3, k: "w" },
  { en: "environment", ipa: "/ɪnˈvaɪrənmənt/", ja: ["環境", "かんきょう"], ex: "We must protect the environment.", exJa: "私たちは環境を守らなければならない。", syn: ["surroundings"], etym: [["en-", "中に"], ["viron", "囲む(virerに由来)"], ["-ment", "〜すること"]], lv: 3, k: "w" },
  { en: "experience", ipa: "/ɪkˈspɪriəns/", ja: ["経験", "体験", "けいけん"], ex: "It was a great experience for me.", exJa: "それは私にとって素晴らしい経験だった。", etym: [["ex-", "外へ"], ["peri", "試す(expeririに由来)"], ["-ence", "〜すること"]], lv: 3, k: "w" },
  { en: "explain", ipa: "/ɪkˈspleɪn/", ja: ["説明", "せつめい"], ex: "Please explain the rule again.", exJa: "そのルールをもう一度説明してください。", syn: ["clarify", "illustrate"], etym: [["ex-", "外へ"], ["plain", "平らにする(planusに由来)"]], lv: 3, k: "w" },
  { en: "express", ipa: "/ɪkˈspres/", ja: ["表現", "表す", "あらわす"], ex: "It's hard to express my feelings.", exJa: "気持ちを表現するのは難しい。", syn: ["convey", "voice"], etym: [["ex-", "外へ"], ["press", "押す"]], lv: 3, k: "w" },
  { en: "government", ipa: "/ˈɡʌvərnmənt/", ja: ["政府", "せいふ"], ex: "The government announced a new policy.", exJa: "政府は新しい政策を発表した。", syn: ["administration"], etym: [["govern", "統治する"], ["-ment", "〜すること"]], lv: 3, k: "w" },
  { en: "include", ipa: "/ɪnˈkluːd/", ja: ["含む", "含める", "ふくむ"], ex: "The price includes tax.", exJa: "価格には税金が含まれています。", syn: ["contain", "comprise"], etym: [["in-", "中に"], ["clude", "閉じる(claudereに由来)"]], lv: 3, k: "w" },
  { en: "knowledge", ipa: "/ˈnɑːlɪdʒ/", ja: ["知識", "ちしき"], ex: "He has a wide knowledge of history.", exJa: "彼は歴史の幅広い知識を持っている。", syn: ["understanding"], etym: [["know", "知る"], ["-ledge", "状態"]], lv: 3, k: "w" },
  { en: "language", ipa: "/ˈlæŋɡwɪdʒ/", ja: ["言語", "言葉", "げんご"], ex: "English is a world language.", exJa: "英語は世界の言語だ。", syn: ["tongue"], etym: [["lang", "舌(linguaに由来)"], ["-age", "〜に関するもの"]], lv: 3, k: "w" },
  { en: "necessary", ipa: "/ˈnesəseri/", ja: ["必要", "ひつよう"], ex: "Sleep is necessary for health.", exJa: "睡眠は健康に必要だ。", syn: ["essential", "required"], etym: [["ne-", "否定"], ["cess", "譲る(cedereに由来)"], ["-ary", "〜の"]], lv: 3, k: "w" },
  { en: "opinion", ipa: "/əˈpɪnjən/", ja: ["意見", "見解", "いけん"], ex: "In my opinion, he is right.", exJa: "私の意見では、彼は正しい。", syn: ["view", "belief"], etym: [["op-", "〜へ(ob-)"], ["pin", "考える(opinariに由来)"], ["-ion", "〜すること"]], lv: 3, k: "w" },
  { en: "opportunity", ipa: "/ˌɑːpərˈtuːnəti/", ja: ["機会", "チャンス", "きかい", "機械"], ex: "Don't miss this opportunity.", exJa: "この機会を逃さないで。", syn: ["chance"], etym: [["op-", "〜へ(ob-)"], ["port", "港"], ["-unity", "状態"]], lv: 3, k: "w" },
  { en: "prepare", ipa: "/prɪˈper/", ja: ["準備", "用意", "じゅんび"], ex: "I'm preparing for the exam.", exJa: "試験の準備をしています。", syn: ["arrange", "get ready"], etym: [["pre-", "前もって"], ["pare", "用意する(parareに由来)"]], lv: 3, k: "w" },
  { en: "protect", ipa: "/prəˈtekt/", ja: ["守る", "保護", "まもる"], ex: "Wear a helmet to protect your head.", exJa: "頭を守るためにヘルメットをかぶりなさい。", syn: ["defend", "guard"], etym: [["pro-", "前に"], ["tect", "覆う(tegereに由来)"]], lv: 3, k: "w" },
  { en: "provide", ipa: "/prəˈvaɪd/", ja: ["提供", "供給", "与える"], ex: "The hotel provides free breakfast.", exJa: "そのホテルは無料の朝食を提供する。", syn: ["supply", "offer"], etym: [["pro-", "前もって"], ["vide", "見る(videreに由来)"]], lv: 3, k: "w" },
  { en: "realize", ipa: "/ˈriːəlaɪz/", ja: ["気づく", "実現", "きづく", "悟る"], ex: "I realized my mistake.", exJa: "自分の間違いに気づいた。", syn: ["recognize", "grasp"], etym: [["real", "現実の"], ["-ize", "〜にする"]], lv: 3, k: "w" },
  { en: "receive", ipa: "/rɪˈsiːv/", ja: ["受け取る", "受ける", "うけとる"], ex: "I received a letter from her.", exJa: "彼女から手紙を受け取った。", syn: ["get", "obtain"], etym: [["re-", "再び"], ["ceive", "取る(capereに由来)"]], lv: 3, k: "w" },
  { en: "reduce", ipa: "/rɪˈduːs/", ja: ["減らす", "削減", "へらす"], ex: "We should reduce plastic waste.", exJa: "プラスチックごみを減らすべきだ。", syn: ["decrease", "cut"], etym: [["re-", "後ろへ"], ["duce", "導く(ducereに由来)"]], lv: 3, k: "w" },
  { en: "require", ipa: "/rɪˈkwaɪər/", ja: ["必要とする", "要求", "求める"], ex: "This job requires experience.", exJa: "この仕事は経験を必要とする。", syn: ["need", "demand"], etym: [["re-", "再び"], ["quire", "求める(quaerereに由来)"]], lv: 3, k: "w" },
  { en: "society", ipa: "/səˈsaɪəti/", ja: ["社会", "しゃかい"], ex: "We live in an aging society.", exJa: "私たちは高齢化社会に生きている。", syn: ["community"], etym: [["soci", "仲間(sociusに由来)"], ["-ety", "状態"]], lv: 3, k: "w" },
  { en: "solve", ipa: "/sɑːlv/", ja: ["解決", "解く", "かいけつ"], ex: "He solved the problem easily.", exJa: "彼はその問題を簡単に解いた。", syn: ["resolve", "work out"], etym: [["se-", "離す"], ["solve", "緩める(solvereに由来)"]], lv: 3, k: "w" },
  { en: "succeed", ipa: "/səkˈsiːd/", ja: ["成功", "せいこう", "後を継ぐ"], ex: "She succeeded in business.", exJa: "彼女はビジネスで成功した。", syn: ["prevail", "flourish"], etym: [["suc-", "下から(sub-)"], ["ceed", "行く(cedereに由来)"]], lv: 3, k: "w" },
  { en: "support", ipa: "/səˈpɔːrt/", ja: ["支える", "支援", "サポート", "ささえる"], ex: "My family supports my dream.", exJa: "家族は私の夢を支えてくれる。", syn: ["assist", "back"], etym: [["sup-", "下から(sub-)"], ["port", "運ぶ"]], lv: 3, k: "w" },
  { en: "various", ipa: "/ˈveriəs/", ja: ["さまざま", "様々", "いろいろ", "多様"], ex: "The store sells various kinds of tea.", exJa: "その店はさまざまな種類のお茶を売っている。", syn: ["diverse", "assorted"], etym: [["vari", "変化する(variusに由来)"], ["-ous", "〜に満ちた"]], lv: 3, k: "w" },
  { en: "recognize", ipa: "/ˈrekəɡnaɪz/", ja: ["認識", "認める", "見分ける", "みとめる"], ex: "I didn't recognize him at first.", exJa: "最初は彼だと気づかなかった。", syn: ["identify", "acknowledge"], etym: [["re-", "再び"], ["cognize", "知る(cognoscereに由来)"]], lv: 3, k: "w" },
  { en: "recently", ipa: "/ˈriːsntli/", ja: ["最近", "近頃", "さいきん"], ex: "I recently moved to Tokyo.", exJa: "最近、東京に引っ越した。", syn: ["lately"], etym: [["re-", "再び"], ["cent", "新しい(recensに由来)"], ["-ly", "〜に"]], lv: 3, k: "w" },
  { en: "attitude", ipa: "/ˈætɪtuːd/", ja: ["態度", "姿勢", "たいど"], ex: "He has a positive attitude.", exJa: "彼は前向きな態度を持っている。", syn: ["mindset", "stance"], etym: [["apt", "適した(aptusに由来)"], ["-itude", "状態"]], lv: 3, k: "w" },
  { en: "influence", ipa: "/ˈɪnfluəns/", ja: ["影響", "えいきょう"], ex: "TV has a big influence on children.", exJa: "テレビは子どもに大きな影響を与える。", syn: ["impact", "effect"], etym: [["in-", "中へ"], ["flu", "流れる(fluereに由来)"], ["-ence", "〜すること"]], lv: 3, k: "w" },
  { en: "purpose", ipa: "/ˈpɜːrpəs/", ja: ["目的", "意図", "もくてき"], ex: "What is the purpose of your visit?", exJa: "訪問の目的は何ですか。", syn: ["aim", "goal"], etym: [["pur-", "前に(pro-)"], ["pose", "置く"]], lv: 3, k: "w" },
  { en: "average", ipa: "/ˈævərɪdʒ/", ja: ["平均", "へいきん"], ex: "The average temperature is rising.", exJa: "平均気温が上昇している。", syn: ["typical", "mean"], etym: [["aver", "損害(海損averiaに由来)"], ["-age", "〜に関するもの"]], lv: 3, k: "w" },

  // ===== Lv4 単語（大学受験） =====
  { en: "abandon", ipa: "/əˈbændən/", ja: ["放棄", "捨てる", "断念", "あきらめる", "見捨てる"], ex: "They abandoned the old plan.", exJa: "彼らは古い計画を断念した。", syn: ["desert", "forsake"], etym: [["a-", "〜の状態に"], ["bandon", "支配・自由裁量(古仏語bandonに由来)"]], lv: 4, k: "w" },
  { en: "accomplish", ipa: "/əˈkɑːmplɪʃ/", ja: ["成し遂げる", "達成", "なしとげる"], ex: "She accomplished the difficult task.", exJa: "彼女はその難しい仕事を成し遂げた。", syn: ["achieve", "fulfill"], etym: [["ac-", "〜へ(ad-)"], ["complish", "満たす・仕上げる(complereに由来)"]], lv: 4, k: "w" },
  { en: "accurate", ipa: "/ˈækjərət/", ja: ["正確", "せいかく", "性格"], ex: "The report is not accurate.", exJa: "その報告は正確ではない。", syn: ["precise", "exact"], etym: [["ac-", "〜へ(ad-)"], ["cur", "注意(curaに由来)"], ["-ate", "〜にされた"]], lv: 4, k: "w" },
  { en: "acquire", ipa: "/əˈkwaɪər/", ja: ["獲得", "習得", "得る", "かくとく"], ex: "He acquired new skills at work.", exJa: "彼は仕事で新しい技術を習得した。", syn: ["obtain", "gain"], etym: [["ac-", "〜へ(ad-)"], ["quire", "求める(quaerereに由来)"]], lv: 4, k: "w" },
  { en: "anticipate", ipa: "/ænˈtɪsɪpeɪt/", ja: ["予期", "予想", "見越す"], ex: "We anticipate a rise in sales.", exJa: "売上の増加を予想している。", syn: ["expect", "foresee"], etym: [["anti-", "前に"], ["cip", "取る(capereに由来)"], ["-ate", "〜する"]], lv: 4, k: "w" },
  { en: "apparent", ipa: "/əˈpærənt/", ja: ["明らか", "見かけ", "あきらか"], ex: "It was apparent that he was tired.", exJa: "彼が疲れているのは明らかだった。", syn: ["evident", "obvious"], etym: [["ap-", "〜へ(ad-)"], ["par", "現れる(parereに由来)"], ["-ent", "〜する"]], lv: 4, k: "w" },
  { en: "significant", ipa: "/sɪɡˈnɪfɪkənt/", ja: ["重要", "重大", "意義深い", "かなりの"], ex: "There was a significant change.", exJa: "重大な変化があった。", syn: ["notable", "considerable"], etym: [["sign", "印(signumに由来)"], ["-ific", "〜にする"], ["-ant", "〜な"]], lv: 4, k: "w" },
  { en: "sufficient", ipa: "/səˈfɪʃnt/", ja: ["十分", "じゅうぶん"], ex: "We have sufficient food for a week.", exJa: "1週間分の十分な食料がある。", syn: ["adequate", "enough"], etym: [["suf-", "下から(sub-)"], ["fic", "作る(facereに由来)"], ["-ient", "〜する"]], lv: 4, k: "w" },
  { en: "temporary", ipa: "/ˈtempəreri/", ja: ["一時的", "仮の", "いちじてき"], ex: "This is only a temporary job.", exJa: "これは一時的な仕事にすぎない。", syn: ["provisional", "short-term"], etym: [["tempor", "時(temposに由来)"], ["-ary", "〜の"]], lv: 4, k: "w" },
  { en: "transform", ipa: "/trænsˈfɔːrm/", ja: ["変換", "変える", "変貌", "一変"], ex: "The internet transformed our lives.", exJa: "インターネットは私たちの生活を一変させた。", syn: ["convert", "alter"], etym: [["trans-", "越えて"], ["form", "形"]], lv: 4, k: "w" },
  { en: "demonstrate", ipa: "/ˈdemənstreɪt/", ja: ["実証", "示す", "証明", "しめす"], ex: "The study demonstrates the effect.", exJa: "その研究は効果を実証している。", syn: ["show", "prove"], etym: [["de-", "強意"], ["monstr", "示す(monstrareに由来)"], ["-ate", "〜する"]], lv: 4, k: "w" },
  { en: "distinguish", ipa: "/dɪˈstɪŋɡwɪʃ/", ja: ["区別", "見分ける", "くべつ"], ex: "Can you distinguish the twins?", exJa: "その双子を見分けられますか。", syn: ["differentiate", "discern"], etym: [["di-", "分離(dis-)"], ["sting", "刺す・印す(stinguereに由来)"], ["-uish", "〜する"]], lv: 4, k: "w" },
  { en: "eliminate", ipa: "/ɪˈlɪmɪneɪt/", ja: ["排除", "取り除く", "削除", "とりのぞく"], ex: "We eliminated all the errors.", exJa: "私たちはすべての誤りを取り除いた。", syn: ["remove", "eradicate"], etym: [["e-", "外へ(ex-)"], ["limin", "敷居(liminisに由来)"], ["-ate", "〜する"]], lv: 4, k: "w" },
  { en: "emphasize", ipa: "/ˈemfəsaɪz/", ja: ["強調", "きょうちょう"], ex: "He emphasized the importance of sleep.", exJa: "彼は睡眠の重要性を強調した。", syn: ["stress", "highlight"], etym: [["em-", "中に(en-)"], ["phas", "見せる(ギリシャ語phaineinに由来)"], ["-ize", "〜する"]], lv: 4, k: "w" },
  { en: "enhance", ipa: "/ɪnˈhæns/", ja: ["高める", "強化", "向上", "たかめる"], ex: "Exercise enhances your health.", exJa: "運動は健康を向上させる。", syn: ["improve", "boost"], etym: [["en-", "〜にする"], ["hance", "高める(altusに由来)"]], lv: 4, k: "w" },
  { en: "evaluate", ipa: "/ɪˈvæljueɪt/", ja: ["評価", "ひょうか"], ex: "Teachers evaluate students' work.", exJa: "教師は生徒の課題を評価する。", syn: ["assess", "appraise"], etym: [["e-", "外へ(ex-)"], ["valu", "価値(valereに由来)"], ["-ate", "〜する"]], lv: 4, k: "w" },
  { en: "predict", ipa: "/prɪˈdɪkt/", ja: ["予測", "予言", "よそく"], ex: "No one can predict the future.", exJa: "誰も未来を予測できない。", syn: ["forecast", "foresee"], etym: [["pre-", "前もって"], ["dict", "言う"]], lv: 4, k: "w" },
  { en: "prohibit", ipa: "/prəˈhɪbɪt/", ja: ["禁止", "きんし"], ex: "Smoking is prohibited in this area.", exJa: "この区域では喫煙が禁止されている。", syn: ["forbid", "ban"], etym: [["pro-", "前に"], ["hibit", "持つ(habereに由来)"]], lv: 4, k: "w" },
  { en: "obstacle", ipa: "/ˈɑːbstəkl/", ja: ["障害", "妨げ", "しょうがい"], ex: "Fear is the biggest obstacle.", exJa: "恐れこそが最大の障害だ。", syn: ["barrier", "hindrance"], etym: [["ob-", "〜に向かって・妨げ"], ["sta", "立つ(stareに由来)"], ["-cle", "もの"]], lv: 4, k: "w" },
  { en: "negotiate", ipa: "/nɪˈɡoʊʃieɪt/", ja: ["交渉", "こうしょう"], ex: "They negotiated a new contract.", exJa: "彼らは新しい契約を交渉した。", syn: ["bargain", "mediate"], etym: [["neg-", "否定"], ["oti", "暇(otiumに由来)"], ["-ate", "〜する"]], lv: 4, k: "w" },
  { en: "imitate", ipa: "/ˈɪmɪteɪt/", ja: ["模倣", "まねる", "真似"], ex: "Children imitate their parents.", exJa: "子どもは親をまねる。", syn: ["mimic", "copy"], etym: [["imit", "似せる(imitariに由来)"], ["-ate", "〜する"]], lv: 4, k: "w" },
  { en: "hypothesis", ipa: "/haɪˈpɑːθəsɪs/", ja: ["仮説", "かせつ"], ex: "The data supports his hypothesis.", exJa: "データは彼の仮説を裏付けている。", syn: ["theory", "assumption"], etym: [["hypo-", "下に"], ["thesis", "置くこと(ギリシャ語)"]], lv: 4, k: "w" },
  { en: "reluctant", ipa: "/rɪˈlʌktənt/", ja: ["気が進まない", "嫌がる", "しぶしぶ", "気乗りしない"], ex: "He was reluctant to answer.", exJa: "彼は答えるのを嫌がった。", syn: ["unwilling", "hesitant"], etym: [["re-", "逆らって"], ["luct", "もがく(luctariに由来)"], ["-ant", "〜な"]], lv: 4, k: "w" },
  { en: "exaggerate", ipa: "/ɪɡˈzædʒəreɪt/", ja: ["誇張", "大げさ", "こちょう", "おおげさ"], ex: "Don't exaggerate the story.", exJa: "話を大げさにしないで。", syn: ["overstate", "embellish"], etym: [["ex-", "外へ"], ["agger", "積み上げる(aggerareに由来)"], ["-ate", "〜する"]], lv: 4, k: "w" },

  // ===== Lv5 単語（上級） =====
  { en: "abolish", ipa: "/əˈbɑːlɪʃ/", ja: ["廃止", "はいし"], ex: "The law was abolished last year.", exJa: "その法律は昨年廃止された。", syn: ["eliminate", "repeal"], etym: [["ab-", "離れて"], ["ol", "育つ(olereに由来)"], ["-ish", "〜にする"]], lv: 5, k: "w" },
  { en: "adequate", ipa: "/ˈædɪkwət/", ja: ["十分", "適切", "じゅうぶん"], ex: "The room has adequate space.", exJa: "その部屋には十分な広さがある。", syn: ["sufficient", "satisfactory"], etym: [["ad-", "〜へ"], ["equ", "等しい(aequusに由来)"], ["-ate", "〜な"]], lv: 5, k: "w" },
  { en: "ambiguous", ipa: "/æmˈbɪɡjuəs/", ja: ["あいまい", "曖昧"], ex: "His answer was ambiguous.", exJa: "彼の答えはあいまいだった。", syn: ["vague", "unclear"], etym: [["ambi-", "両方に"], ["ig", "導く(agereに由来)"], ["-uous", "〜な"]], lv: 5, k: "w" },
  { en: "inevitable", ipa: "/ɪnˈevɪtəbl/", ja: ["避けられない", "必然", "さけられない"], ex: "Change is inevitable.", exJa: "変化は避けられない。", syn: ["unavoidable", "certain"], etym: [["in-", "否定"], ["evit", "避ける(evitareに由来)"], ["-able", "〜できる"]], lv: 5, k: "w" },
  { en: "undermine", ipa: "/ˌʌndərˈmaɪn/", ja: ["弱める", "損なう", "むしばむ", "そこなう"], ex: "Stress can undermine your health.", exJa: "ストレスは健康を損なうことがある。", syn: ["weaken", "sabotage"], etym: [["under-", "下を"], ["mine", "掘る"]], lv: 5, k: "w" },
  { en: "vague", ipa: "/veɪɡ/", ja: ["あいまい", "曖昧", "漠然"], ex: "I have only a vague memory of it.", exJa: "それについては漠然とした記憶しかない。", syn: ["unclear", "ambiguous"], etym: [["vag", "さまよう(vagariに由来)"]], lv: 5, k: "w" },
  { en: "withstand", ipa: "/wɪðˈstænd/", ja: ["耐える", "持ちこたえる", "たえる"], ex: "This building can withstand earthquakes.", exJa: "この建物は地震に耐えられる。", syn: ["endure", "resist"], etym: [["with-", "逆らって"], ["stand", "立つ"]], lv: 5, k: "w" },
  { en: "compensate", ipa: "/ˈkɑːmpenseɪt/", ja: ["補償", "補う", "埋め合わせ", "おぎなう"], ex: "Nothing can compensate for the loss.", exJa: "その損失は何をもってしても補えない。", syn: ["reimburse", "offset"], etym: [["com-", "共に"], ["pens", "量る・支払う(pendereに由来)"], ["-ate", "〜する"]], lv: 5, k: "w" },
  { en: "comprehensive", ipa: "/ˌkɑːmprɪˈhensɪv/", ja: ["包括的", "総合的", "ほうかつてき"], ex: "We need a comprehensive plan.", exJa: "包括的な計画が必要だ。", syn: ["thorough", "extensive"], etym: [["com-", "共に"], ["prehens", "つかむ(prehendereに由来)"], ["-ive", "〜な"]], lv: 5, k: "w" },
  { en: "contradict", ipa: "/ˌkɑːntrəˈdɪkt/", ja: ["矛盾", "むじゅん", "反論"], ex: "His actions contradict his words.", exJa: "彼の行動は言葉と矛盾している。", syn: ["oppose", "counter"], etym: [["contra-", "反対に"], ["dict", "言う"]], lv: 5, k: "w" },
  { en: "deliberate", ipa: "/dɪˈlɪbərət/", ja: ["意図的", "故意", "慎重"], ex: "It was a deliberate lie.", exJa: "それは意図的な嘘だった。", syn: ["intentional", "calculated"], etym: [["de-", "強意"], ["liber", "天秤(libraに由来)"], ["-ate", "〜にする"]], lv: 5, k: "w" },
  { en: "derive", ipa: "/dɪˈraɪv/", ja: ["由来", "引き出す", "得る", "ゆらい"], ex: "This word derives from Latin.", exJa: "この単語はラテン語に由来する。", syn: ["originate", "stem"], etym: [["de-", "下へ"], ["rive", "川(rivusに由来)"]], lv: 5, k: "w" },
  { en: "devastate", ipa: "/ˈdevəsteɪt/", ja: ["荒廃", "打ちのめす", "壊滅"], ex: "The storm devastated the town.", exJa: "嵐が町を壊滅させた。", syn: ["destroy", "ravage"], etym: [["de-", "完全に"], ["vast", "荒れた(vastusに由来)"], ["-ate", "〜する"]], lv: 5, k: "w" },
  { en: "diminish", ipa: "/dɪˈmɪnɪʃ/", ja: ["減少", "減らす", "小さくする", "弱まる"], ex: "His influence has diminished.", exJa: "彼の影響力は弱まった。", syn: ["decrease", "lessen"], etym: [["di-", "分離(dis-)"], ["min", "小さい(minorに由来)"], ["-ish", "〜にする"]], lv: 5, k: "w" },
  { en: "facilitate", ipa: "/fəˈsɪlɪteɪt/", ja: ["促進", "容易にする", "そくしん"], ex: "The app facilitates communication.", exJa: "そのアプリはコミュニケーションを容易にする。", syn: ["ease", "simplify"], etym: [["facil", "容易な(facilisに由来)"], ["-itate", "〜にする"]], lv: 5, k: "w" },
  { en: "fluctuate", ipa: "/ˈflʌktʃueɪt/", ja: ["変動", "上下する", "へんどう"], ex: "Prices fluctuate daily.", exJa: "価格は日々変動する。", syn: ["vary", "oscillate"], etym: [["fluctu", "波(fluctusに由来)"], ["-ate", "〜する"]], lv: 5, k: "w" },
  { en: "implement", ipa: "/ˈɪmplɪment/", ja: ["実行", "実施", "導入", "じっし"], ex: "The company implemented a new system.", exJa: "その会社は新しいシステムを導入した。", syn: ["execute", "carry out"], etym: [["im-", "中に(in-)"], ["ple", "満たす(plereに由来)"], ["-ment", "もの・こと"]], lv: 5, k: "w" },
  { en: "imply", ipa: "/ɪmˈplaɪ/", ja: ["ほのめかす", "暗示", "示唆", "あんじ"], ex: "Her smile implied agreement.", exJa: "彼女の笑顔は同意を暗示していた。", syn: ["suggest", "hint"], etym: [["im-", "中に(in-)"], ["ply", "折りたたむ(plicareに由来)"]], lv: 5, k: "w" },
  { en: "indispensable", ipa: "/ˌɪndɪˈspensəbl/", ja: ["不可欠", "欠かせない", "ふかけつ"], ex: "Water is indispensable to life.", exJa: "水は生命に不可欠だ。", syn: ["essential", "vital"], etym: [["in-", "否定"], ["dispens", "分配する・免除する(dispensareに由来)"], ["-able", "〜できる"]], lv: 5, k: "w" },
  { en: "inhibit", ipa: "/ɪnˈhɪbɪt/", ja: ["抑制", "妨げる", "よくせい"], ex: "Fear inhibits free discussion.", exJa: "恐れは自由な議論を妨げる。", syn: ["restrain", "hinder"], etym: [["in-", "中に"], ["hibit", "持つ(habereに由来)"]], lv: 5, k: "w" },
  { en: "legitimate", ipa: "/lɪˈdʒɪtɪmət/", ja: ["合法", "正当", "せいとう"], ex: "That is a legitimate question.", exJa: "それは正当な質問だ。", syn: ["valid", "lawful"], etym: [["leg", "法(lexに由来)"], ["-itimate", "〜にされた"]], lv: 5, k: "w" },
  { en: "manipulate", ipa: "/məˈnɪpjuleɪt/", ja: ["操作", "操る", "あやつる"], ex: "He tried to manipulate the data.", exJa: "彼はデータを操作しようとした。", syn: ["control", "influence"], etym: [["mani", "手(manusに由来)"], ["-pulate", "扱う"]], lv: 5, k: "w" },
  { en: "persist", ipa: "/pərˈsɪst/", ja: ["固執", "持続", "続く", "こだわる"], ex: "If the pain persists, see a doctor.", exJa: "痛みが続くなら医者に診てもらいなさい。", syn: ["continue", "persevere"], etym: [["per-", "徹底して"], ["sist", "立つ(sistereに由来)"]], lv: 5, k: "w" },
  { en: "plausible", ipa: "/ˈplɔːzəbl/", ja: ["もっともらしい", "妥当", "ありそう"], ex: "His explanation sounds plausible.", exJa: "彼の説明はもっともらしく聞こえる。", syn: ["credible", "believable"], etym: [["plaus", "拍手する(plaudereに由来)"], ["-ible", "〜できる"]], lv: 5, k: "w" },

  // ===== Lv1 熟語 =====
  { en: "give up", ja: ["あきらめる", "諦める", "やめる"], ex: "Don't give up on your dream.", exJa: "夢をあきらめないで。", syn: ["quit", "abandon"], etym: [["give", "与える"], ["up", "手放して・完全に"]], lv: 1, k: "i" },
  { en: "look for", ja: ["探す", "さがす"], ex: "I'm looking for my keys.", exJa: "鍵を探しています。", syn: ["seek", "search for"], etym: [["look", "見る"], ["for", "〜を求めて"]], lv: 1, k: "i" },
  { en: "get up", ja: ["起きる", "起床", "おきる"], ex: "I get up at six every day.", exJa: "毎日6時に起きます。", syn: ["rise", "wake up"], etym: [["get", "なる"], ["up", "上へ"]], lv: 1, k: "i" },
  { en: "put on", ja: ["着る", "身につける", "きる"], ex: "Put on your coat. It's cold.", exJa: "コートを着なさい。寒いよ。", syn: ["wear"], etym: [["put", "置く"], ["on", "上に接触して"]], lv: 1, k: "i" },
  { en: "take off", ja: ["脱ぐ", "離陸", "ぬぐ", "りりく"], ex: "Please take off your shoes here.", exJa: "ここで靴を脱いでください。", syn: ["remove"], etym: [["take", "取る"], ["off", "離して"]], lv: 1, k: "i" },
  { en: "turn on", ja: ["つける", "電源を入れる", "点ける"], ex: "Turn on the light, please.", exJa: "電気をつけてください。", syn: ["switch on"], etym: [["turn", "回す・向ける"], ["on", "作動状態に"]], lv: 1, k: "i" },
  { en: "turn off", ja: ["消す", "電源を切る", "けす"], ex: "Turn off the TV before bed.", exJa: "寝る前にテレビを消しなさい。", syn: ["switch off"], etym: [["turn", "回す・向ける"], ["off", "停止状態に"]], lv: 1, k: "i" },
  { en: "pick up", ja: ["拾う", "迎えに行く", "ひろう", "むかえ"], ex: "I'll pick you up at the station.", exJa: "駅まで迎えに行くよ。", syn: ["collect", "fetch"], etym: [["pick", "つまむ・選ぶ"], ["up", "上へ"]], lv: 1, k: "i" },

  // ===== Lv2 熟語 =====
  { en: "look forward to", ja: ["楽しみに", "たのしみに"], ex: "I'm looking forward to seeing you.", exJa: "あなたに会えるのを楽しみにしています。", syn: ["anticipate", "await"], etym: [["look", "見る"], ["forward", "前方へ"], ["to", "〜に向けて"]], lv: 2, k: "i" },
  { en: "take care of", ja: ["世話", "面倒を見る", "せわ", "めんどう"], ex: "She takes care of her little brother.", exJa: "彼女は弟の世話をしている。", syn: ["look after", "attend to"], etym: [["take", "取る"], ["care", "注意・世話"], ["of", "〜の"]], lv: 2, k: "i" },
  { en: "be interested in", ja: ["興味がある", "関心がある", "きょうみ"], ex: "I'm interested in Japanese history.", exJa: "日本の歴史に興味があります。", syn: ["care about"], etym: [["be", "である"], ["interested", "興味を持った"], ["in", "〜の中に"]], lv: 2, k: "i" },
  { en: "be good at", ja: ["得意", "上手", "とくい", "じょうず"], ex: "He is good at playing soccer.", exJa: "彼はサッカーが得意だ。", syn: ["excel at"], etym: [["be", "である"], ["good", "良い"], ["at", "〜の点で"]], lv: 2, k: "i" },

  // ===== Lv3 熟語 =====
  { en: "come up with", ja: ["思いつく", "考え出す", "おもいつく"], ex: "She came up with a great idea.", exJa: "彼女は素晴らしいアイデアを思いついた。", syn: ["devise", "think of"], etym: [["come", "来る"], ["up", "浮かび上がって"], ["with", "〜を伴って"]], lv: 3, k: "i" },
  { en: "carry out", ja: ["実行", "実施", "じっこう"], ex: "They carried out the plan.", exJa: "彼らはその計画を実行した。", syn: ["execute", "perform"], etym: [["carry", "運ぶ"], ["out", "最後まで"]], lv: 3, k: "i" },
  { en: "deal with", ja: ["対処", "扱う", "たいしょ", "あつかう"], ex: "How do you deal with stress?", exJa: "ストレスにどう対処していますか。", syn: ["handle", "address"], etym: [["deal", "分配する・扱う"], ["with", "〜を"]], lv: 3, k: "i" },
  { en: "depend on", ja: ["頼る", "次第", "依存", "たよる"], ex: "It depends on the weather.", exJa: "それは天気次第です。", syn: ["rely on", "count on"], etym: [["de-", "下に"], ["pend", "ぶら下がる"], ["on", "〜に"]], lv: 3, k: "i" },
  { en: "figure out", ja: ["理解する", "解決する", "わかる", "見つけ出す"], ex: "I can't figure out this problem.", exJa: "この問題が理解できない。", syn: ["work out", "understand"], etym: [["figure", "形作る"], ["out", "はっきりと"]], lv: 3, k: "i" },
  { en: "find out", ja: ["見つけ出す", "発見", "知る", "突き止める"], ex: "I found out the truth at last.", exJa: "ついに真実を知った。", syn: ["discover", "learn"], etym: [["find", "見つける"], ["out", "すっかり"]], lv: 3, k: "i" },
  { en: "get along with", ja: ["仲良く", "うまくやる", "なかよく"], ex: "I get along with my classmates.", exJa: "クラスメートと仲良くやっています。", syn: ["get on with"], etym: [["get", "進む"], ["along", "沿って"], ["with", "〜と"]], lv: 3, k: "i" },
  { en: "get rid of", ja: ["取り除く", "処分", "とりのぞく"], ex: "I want to get rid of old clothes.", exJa: "古い服を処分したい。", syn: ["dispose of", "discard"], etym: [["get", "得る"], ["rid", "取り除かれた"], ["of", "〜から"]], lv: 3, k: "i" },
  { en: "give in", ja: ["屈する", "降参", "こうさん", "折れる"], ex: "He never gives in to pressure.", exJa: "彼は決して圧力に屈しない。", syn: ["surrender", "yield"], etym: [["give", "与える"], ["in", "中へ・屈して"]], lv: 3, k: "i" },
  { en: "go through", ja: ["経験", "通り抜ける", "けいけん"], ex: "She went through a hard time.", exJa: "彼女はつらい時期を経験した。", syn: ["undergo", "experience"], etym: [["go", "行く"], ["through", "通り抜けて"]], lv: 3, k: "i" },
  { en: "hand in", ja: ["提出", "ていしゅつ"], ex: "Hand in your homework by Friday.", exJa: "金曜日までに宿題を提出しなさい。", syn: ["submit", "turn in"], etym: [["hand", "手渡す"], ["in", "中へ"]], lv: 3, k: "i" },
  { en: "look after", ja: ["世話", "面倒を見る", "せわ"], ex: "Can you look after my dog?", exJa: "犬の面倒を見てくれますか。", syn: ["take care of", "tend"], etym: [["look", "見る"], ["after", "後を追って"]], lv: 3, k: "i" },
  { en: "look up to", ja: ["尊敬", "そんけい"], ex: "I look up to my grandfather.", exJa: "私は祖父を尊敬している。", syn: ["admire", "respect"], etym: [["look", "見る"], ["up", "上へ"], ["to", "〜に"]], lv: 3, k: "i" },
  { en: "look down on", ja: ["見下す", "軽蔑", "みくだす", "けいべつ"], ex: "Don't look down on others.", exJa: "他人を見下してはいけない。", syn: ["despise", "scorn"], etym: [["look", "見る"], ["down", "下へ"], ["on", "〜の上に"]], lv: 3, k: "i" },
  { en: "make up for", ja: ["埋め合わせ", "補う", "うめあわせ", "おぎなう"], ex: "I'll make up for the lost time.", exJa: "失った時間を埋め合わせます。", syn: ["compensate for", "offset"], etym: [["make", "作る"], ["up", "満たして"], ["for", "〜のために"]], lv: 3, k: "i" },
  { en: "put off", ja: ["延期", "先延ばし", "えんき"], ex: "The game was put off until Sunday.", exJa: "試合は日曜日に延期された。", syn: ["postpone", "delay"], etym: [["put", "置く"], ["off", "離して・先に"]], lv: 3, k: "i" },
  { en: "put up with", ja: ["我慢", "耐える", "がまん", "たえる"], ex: "I can't put up with the noise.", exJa: "その騒音には我慢できない。", syn: ["tolerate", "endure"], etym: [["put", "置く"], ["up", "耐えて"], ["with", "〜と共に"]], lv: 3, k: "i" },
  { en: "run out of", ja: ["使い果たす", "切らす", "なくなる", "尽きる"], ex: "We ran out of milk.", exJa: "牛乳を切らしてしまった。", syn: ["deplete", "exhaust"], etym: [["run", "尽きる"], ["out", "外へ"], ["of", "〜から"]], lv: 3, k: "i" },
  { en: "set up", ja: ["設立", "設置", "準備", "せつりつ"], ex: "They set up a new company.", exJa: "彼らは新しい会社を設立した。", syn: ["establish", "found"], etym: [["set", "据える"], ["up", "立てて"]], lv: 3, k: "i" },
  { en: "show up", ja: ["現れる", "姿を見せる", "あらわれる", "来る"], ex: "He didn't show up at the meeting.", exJa: "彼は会議に現れなかった。", syn: ["appear", "arrive"], etym: [["show", "見せる"], ["up", "現れて"]], lv: 3, k: "i" },
  { en: "take after", ja: ["似ている", "にている"], ex: "She takes after her mother.", exJa: "彼女は母親に似ている。", syn: ["resemble"], etym: [["take", "取る"], ["after", "〜の後に続いて"]], lv: 3, k: "i" },
  { en: "take part in", ja: ["参加", "さんか"], ex: "I took part in the contest.", exJa: "私はそのコンテストに参加した。", syn: ["participate in", "join"], etym: [["take", "取る"], ["part", "役割・部分"], ["in", "〜の中で"]], lv: 3, k: "i" },
  { en: "turn down", ja: ["断る", "却下", "ことわる", "音量を下げる"], ex: "She turned down the offer.", exJa: "彼女はその申し出を断った。", syn: ["reject", "decline"], etym: [["turn", "向ける"], ["down", "下へ・拒んで"]], lv: 3, k: "i" },

  // ===== Lv4 熟語 =====
  { en: "account for", ja: ["説明する", "占める", "しめる"], ex: "Exports account for 40% of sales.", exJa: "輸出が売上の40%を占める。", syn: ["explain", "represent"], etym: [["account", "説明する・計算する"], ["for", "〜について"]], lv: 4, k: "i" },
  { en: "bring about", ja: ["引き起こす", "もたらす", "ひきおこす"], ex: "The war brought about great changes.", exJa: "戦争は大きな変化をもたらした。", syn: ["cause", "trigger"], etym: [["bring", "もたらす"], ["about", "生じさせて"]], lv: 4, k: "i" },
  { en: "call off", ja: ["中止", "取りやめ", "ちゅうし"], ex: "The event was called off due to rain.", exJa: "イベントは雨のため中止された。", syn: ["cancel"], etym: [["call", "呼ぶ"], ["off", "中止して"]], lv: 4, k: "i" },
  { en: "come across", ja: ["偶然出会う", "出くわす", "ぐうぜん", "見つける"], ex: "I came across an old friend.", exJa: "旧友に偶然出会った。", syn: ["encounter", "stumble upon"], etym: [["come", "来る"], ["across", "横切って"]], lv: 4, k: "i" },
  { en: "drop by", ja: ["立ち寄る", "たちよる"], ex: "Drop by my office anytime.", exJa: "いつでも私のオフィスに立ち寄ってください。", syn: ["stop by", "visit"], etym: [["drop", "ふらっと訪れる"], ["by", "そばに"]], lv: 4, k: "i" },
  { en: "fall behind", ja: ["遅れる", "後れを取る", "おくれる"], ex: "He fell behind in his studies.", exJa: "彼は勉強で遅れを取った。", syn: ["lag behind"], etym: [["fall", "落ちる"], ["behind", "後ろに"]], lv: 4, k: "i" },
  { en: "live up to", ja: ["期待に応える", "沿う", "こたえる"], ex: "The movie lived up to my expectations.", exJa: "その映画は期待に応えてくれた。", syn: ["fulfill", "meet"], etym: [["live", "生きる"], ["up", "十分な水準に"], ["to", "〜に"]], lv: 4, k: "i" },
  { en: "take over", ja: ["引き継ぐ", "乗っ取る", "ひきつぐ"], ex: "She took over the family business.", exJa: "彼女は家業を引き継いだ。", syn: ["assume control of"], etym: [["take", "取る"], ["over", "引き継いで"]], lv: 4, k: "i" },
  { en: "turn out", ja: ["判明", "だとわかる", "はんめい", "結局"], ex: "The rumor turned out to be true.", exJa: "そのうわさは本当だと判明した。", syn: ["prove to be", "result"], etym: [["turn", "向く"], ["out", "結局は"]], lv: 4, k: "i" },
  { en: "work out", ja: ["解決", "うまくいく", "運動", "かいけつ"], ex: "Everything worked out fine.", exJa: "すべてうまくいった。", syn: ["resolve", "exercise"], etym: [["work", "働く"], ["out", "結果として"]], lv: 4, k: "i" },

  // ===== Lv5 熟語 =====
  { en: "do away with", ja: ["廃止", "取り除く", "はいし"], ex: "We should do away with this rule.", exJa: "この規則は廃止すべきだ。", syn: ["abolish", "eliminate"], etym: [["do", "する"], ["away", "取り去って"], ["with", "〜を"]], lv: 5, k: "i" },
  { en: "hold back", ja: ["抑える", "ためらう", "おさえる", "隠す"], ex: "She held back her tears.", exJa: "彼女は涙をこらえた。", syn: ["restrain", "suppress"], etym: [["hold", "保つ"], ["back", "後ろに抑えて"]], lv: 5, k: "i" },
  { en: "make out", ja: ["理解する", "見分ける", "わかる"], ex: "I couldn't make out what he said.", exJa: "彼の言ったことが理解できなかった。", syn: ["discern", "understand"], etym: [["make", "作る"], ["out", "理解して・判読して"]], lv: 5, k: "i" },
  { en: "rule out", ja: ["除外", "排除", "じょがい"], ex: "We can't rule out that possibility.", exJa: "その可能性は除外できない。", syn: ["exclude", "eliminate"], etym: [["rule", "定める・裁定する"], ["out", "除外して"]], lv: 5, k: "i" },
  { en: "stand for", ja: ["表す", "意味する", "あらわす", "我慢"], ex: "What does AI stand for?", exJa: "AIは何を表していますか。", syn: ["represent", "symbolize"], etym: [["stand", "立つ"], ["for", "〜を代表して"]], lv: 5, k: "i" },
];

// 各エントリに一意IDを付与（en + 種別）
WORDS.forEach(w => { w.id = w.k + ":" + w.en; });
